const galleryData = {
    poster: [
        { src: 'img/design/poster/cover.png', title: 'Burning Skeleton in Priests Robes' },
        { src: 'img/design/poster/cdcoverfront.png', title: 'Children of the Future Event Poster' },
        { src: 'img/design/poster/MEGAZINE COVER PBL2.png', title: 'Man in Suit on Cover of Magazine' },
        { src: 'img/design/poster/p.jpg', title: 'Restaurant Menu Poster for Meat Lovers' },
        { src: 'img/design/poster/p (1).jpg', title: 'Gaming Tournament Poster for Menjerit Event' },
        { src: 'img/design/poster/p (2).jpg', title: 'Plastic Bersih Campaign Rice and Chicken Offer for RM10.00' },
        { src: 'img/design/poster/p (3).jpg', title: 'Rice and Meat Promo Menu Ad' },
        { src: 'img/design/poster/p (4).jpg', title: 'Food Promotion Poster for Daging Goreng Kuning at RM 10.00' },
        { src: 'img/design/poster/p (5).jpg', title: 'Adobo Mixed Rice Menu Sign with Black Pepper and Beef Stir Fry' },
        { src: 'img/design/poster/p (6).jpg', title: 'Rice and Beef Meal Advertisement' },
        { src: 'img/design/poster/palestineproject6.png', title: 'Protestors raising flags at sunset.' },
        { src: 'img/design/poster/panglimas.png', title: 'Dragon Force Malaysia Team Photo' },
        { src: 'img/design/poster/plastik.jpg', title: 'Indonesian Street Food Menu Poster' },
        { src: 'img/design/poster/poster (1).jpg', title: 'Album Cover for Devi Productions Albumabah' },
        { src: 'img/design/poster/poster (1).png', title: 'JDragon Sneaker Box Design' },
        { src: 'img/design/poster/poster (2).jpg', title: 'Luxurious Perfume Collection Display' },
        { src: 'img/design/poster/poster (2).png', title: 'Bright Red Box Truck Advertisement Secret... Why Not?' },
        { src: 'img/design/poster/poster (3).jpg', title: 'Skadis Mobile Organizer Advertisement Image' },
        { src: 'img/design/poster/poster (3).png', title: 'ABU - Animated Movie Poster' },
        { src: 'img/design/poster/poster (4).jpg', title: 'Vaping Hardware Accessories Set' },
        { src: 'img/design/poster/poster (4).png', title: 'Abu Film Poster' },
        { src: 'img/design/poster/poster (5).jpg', title: 'Skadicals Infinite Configurations Poster' },
        { src: 'img/design/poster/poster (5).png', title: 'Anime Car Poster for My Tears Turned into a Sea' },
        { src: 'img/design/poster/poster (6).jpg', title: 'Nurturing Culture Empowering Minds Campaign Poster' },
        { src: 'img/design/poster/poster (6).png', title: 'My Friends Are Coming to Abu Dhabi Anime Poster' },
        { src: 'img/design/poster/poster (7).jpg', title: 'Spicy Cheese Powder for Sale - RM10 Only!' },
        { src: 'img/design/poster/poster (7).png', title: 'Movie Poster for Animated Drama Film: My Tears Came From Being Born Into a Slum' },
        { src: 'img/design/poster/poster (8).jpg', title: 'Call for Food Sponsors Event Poster - October 2019' },
        { src: 'img/design/poster/poster (8).png', title: 'Skull Clad in Costume with Dangling Ribs' },
        { src: 'img/design/poster/poster (9).jpg', title: 'Grammy Awards Poster with Music and Design Elements' },
        { src: 'img/design/poster/poster (9).png', title: 'Skeletal Figure in Costume Holding Banner' },
        { src: 'img/design/poster/poster (10).png', title: 'Batting Helmet Pitching Machine Baseball Sports Equipment' },
        { src: 'img/design/poster/poster (11).png', title: 'Electric Skull DJ Album Cover' },
        { src: 'img/design/poster/poster (12).png', title: 'Tattooed Man Wearing a Skull Mask' },
        { src: 'img/design/poster/poster (13).PNG', title: 'Famous Politicians and Cityscape Poster' },
        { src: 'img/design/poster/poster (14).png', title: 'Tennis Player in Outer Space Advertisement' },
        { src: 'img/design/poster/poster (15).png', title: 'Political Satire Poster Featuring Character' },
        { src: 'img/design/poster/poster (16).PNG', title: 'Indian Man in Suit Holding Gun' },
        { src: 'img/design/poster/poster (17).PNG', title: 'Hulk in Library With Sports Fans' },
        { src: 'img/design/poster/poster (18).png', title: 'Young man immersed in reading amidst towering books.' },
        { src: 'img/design/poster/poster (19).PNG', title: 'Childrens Refuge in War Zone' },
        { src: 'img/design/poster/poster (20).PNG', title: 'Menjerit Movie Poster' },
        { src: 'img/design/poster/poster (21).PNG', title: 'Malaysia National Day Celebration Poster' },
        { src: 'img/design/poster/POSTER.jpg', title: 'Multimedia Art Showcase Poster with Artist and Date' },
        { src: 'img/design/poster/poster.png', title: 'Woman in Magazine with Headscarf and Suit' },
        { src: 'img/design/poster/poster5.png', title: 'Grafika Poster for Graphic Design Workshop 2023' },
        { src: 'img/design/poster/poster6.png', title: 'Graphika Poster - Dewa At Seni Concert' },
        { src: 'img/design/poster/POSTERV5.png', title: 'Children of the Future: Celebration for Childrens Day 2021.' },
        { src: 'img/design/poster/shame.PNG', title: 'Man under fire with Star of David mask.' },
        { src: 'img/design/poster/watermerdeka4-6.png', title: 'Man Holding Malaysia and USA Flags in Water' },
    ],
    jersey: [
        { src: 'img/design/jersey/cover.jpg', title: 'Malaysia Royal Soccer Jersey Design' },
        { src: 'img/design/jersey/jersey.jpg', title: 'Architecture Jersey Concept by Zizi Brothers' },
        { src: 'img/design/jersey/jersey (1).jpg', title: 'Brave Racing Jerseys by VERTICO.' },
        { src: 'img/design/jersey/jersey (1).png', title: 'Limited Edition University Malaysia T-shirt Design Advertisement with Contact Information' },
        { src: 'img/design/jersey/jersey (2).jpg', title: 'Vertix Gaming Jersey Design' },
        { src: 'img/design/jersey/jersey (2).png', title: 'Official Gaming Jersey - Dynite Sports' },
        { src: 'img/design/jersey/jersey (3).jpg', title: 'NFL Pro Line by Fanatics Branded Custom Jersey Design.' },
        { src: 'img/design/jersey/jersey (3).png', title: 'Red and black soccer jersey featuring USA logo on chest.' },
        { src: 'img/design/jersey/jersey (4).jpg', title: 'Football Jersey Design Featuring Vertico Team Colors and Numbers' },
        { src: 'img/design/jersey/jersey (4).png', title: 'Futuristic Sports Jersey Concept Design' },
        { src: 'img/design/jersey/jersey (5).jpg', title: 'Black and White Striped Soccer Jersey' },
        { src: 'img/design/jersey/jersey (6).jpg', title: 'Vertico Custom Soccer Jersey Design' },
        { src: 'img/design/jersey/jersey (7).jpg', title: 'Vertico Jersey Design #6 Sleeve.' },
        { src: 'img/design/jersey/jersey (8).jpg', title: 'Customized Vertico Jersey Design with Lightning Prints' },
        { src: 'img/design/jersey/jersey (9).jpg', title: 'Custom Vertico Name Jersey Samples' },
        { src: 'img/design/jersey/jersey (10).jpg', title: 'Green Vectico sports jersey with motivational slogan and logo.' },
        { src: 'img/design/jersey/jersey (11).jpg', title: 'Pink Nike VERTCO Jersey with Embroidered Number 21' },
        { src: 'img/design/jersey/jersey (12).jpg', title: 'Custom Vertico Jersey Design featuring Blue and White with a Monkey Logo.' },
        { src: 'img/design/jersey/jersey (13).jpg', title: 'Vertico Jersey Design Concept' },
        { src: 'img/design/jersey/jersey (14).jpg', title: 'Yellow and black sports jersey with LIMITLESS slogan.' },
        { src: 'img/design/jersey/jersey (15).jpg', title: 'Vertico Football Kit Personalization Advertisement' },
        { src: 'img/design/jersey/jersey (16).jpg', title: 'Vertico custom jersey design with pink color and Name on back.' },
        { src: 'img/design/jersey/jersey (17).jpg', title: 'Vertico Pink Jersey Design with Customization Details' },
        { src: 'img/design/jersey/jersey (18).jpg', title: 'Custom NHL Hockey Jersey Design Showcase' },
        { src: 'img/design/jersey/jersey (19).jpg', title: 'New Zealand Rugby Jersey Design with Vertico Advertisement' },
        { src: 'img/design/jersey/jersey (20).jpg', title: 'Custom Menjerit Jersey Design by Vertico with Mountain and River Pattern' },
        { src: 'img/design/jersey/jersey (21).jpg', title: 'Vertico Customizable Jersey Design with Slogan and Team Logos' },
        { src: 'img/design/jersey/jersey (22).jpg', title: 'Green and Yellow Soccer Jersey' },
        { src: 'img/design/jersey/jersey (23).jpg', title: 'Custom VERTICO Soccer Jersey for Player #10' },
        { src: 'img/design/jersey/jersey (24).jpg', title: 'Vertigo Custom Soccer Jersey with Name and Number' },
        { src: 'img/design/jersey/jersey (25).jpg', title: 'Customized Soccer Jersey featuring Vertico and a players name.' },
        { src: 'img/design/jersey/jersey (26).jpg', title: 'Vertico Team Soccer Jersey' },
        { src: 'img/design/jersey/jersey (27).jpg', title: 'Vertico.com Adidas Soccer Jersey Display' },
        { src: 'img/design/jersey/jersey (28).jpg', title: 'Victoria Striped Soccer Jersey' },
        { src: 'img/design/jersey/jersey (29).jpg', title: 'Yellow and Blue Football Shirt Concept for Verteco Team' },
        { src: 'img/design/jersey/jersey (30).jpg', title: 'Vertico Limitless Soccer Jersey Design' },
        { src: 'img/design/jersey/jersey (31).jpg', title: 'Blue and white soccer jersey mockup.' },
        { src: 'img/design/jersey/jersey (32).jpg', title: 'Customizable Soccer Jersey with Vertical Design' },
        { src: 'img/design/jersey/jersey (33).jpg', title: 'Customized Green and White Football Jersey with Name and Number.' },
        { src: 'img/design/jersey/jersey (34).jpg', title: 'Vertico Custom Soccer Jersey with Name and Number on Rear' },
        { src: 'img/design/jersey/jersey (35).jpg', title: 'Yellow and orange football jersey' },
        { src: 'img/design/jersey/jersey (36).jpg', title: 'Versatile Jersey Design for Vertico Team' },
        { src: 'img/design/jersey/jersey (37).jpg', title: 'Soccer Jersey Design - Customizable Name and Number' },
        { src: 'img/design/jersey/jersey (38).jpg', title: 'Fridas VERTICO Gaming Jersey Concept' },
        { src: 'img/design/jersey/jersey (39).jpg', title: 'Vertico Jersey Concept for Customized Name and Number.' },
        { src: 'img/design/jersey/jersey (40).jpg', title: 'Vertico Custom Jersey Concept' },
        { src: 'img/design/jersey/jersey (41).jpg', title: 'Custom VERTICO Jersey Design in Blue and Black.' },
        { src: 'img/design/jersey/jersey (42).jpg', title: 'Vertico Jersey Design with Patterns and Logos' },
        { src: 'img/design/jersey/jersey (43).jpg', title: 'Vertice Custom Football Jersey Design' },
        { src: 'img/design/jersey/jersey (44).jpg', title: 'VECTIO. Vertical. Racing. Jersey. Design.' },
        { src: 'img/design/jersey/jersey (45).jpg', title: 'Vertico Jersey Design Concept' },
        { src: 'img/design/jersey/jersey (46).jpg', title: 'Soccer Jersey Design for Vertico Team' },
        { src: 'img/design/jersey/jersey (47).jpg', title: 'Custom VERTICO floral patterned sports jerseys' },
        { src: 'img/design/jersey/jersey (48).jpg', title: 'Vertico: Custom Green & White Uniforms' },
        { src: 'img/design/jersey/jersey (49).jpg', title: 'Baseball Jersey Display Featuring Mariah' },
        { src: 'img/design/jersey/jersey (50).jpg', title: 'Vertico Cosmic Sports Jerseys for Team Unity' },
        { src: 'img/design/jersey/jersey (51).jpg', title: 'Pink and Blue Vertix Crew T-Shirt Display' },
        { src: 'img/design/jersey/jersey (52).jpg', title: 'Vertico. Limited Edition Football Jersey Designed for Performance and Style' },
        { src: 'img/design/jersey/jersey (53).jpg', title: 'Team Jersey Design Featuring Custom Graphic and Text' },
        { src: 'img/design/jersey/jersey (54).jpg', title: 'Flaming Tiger Football Jersey Design' },
        { src: 'img/design/jersey/jersey (55).jpg', title: 'Vertico Jersey Design for Phoenix Ft. Storm Team' },
        { src: 'img/design/jersey/jersey (56).jpg', title: 'Vertico.com Football Jersey Display' },
        { src: 'img/design/jersey/jersey (57).jpg', title: 'Customizable Vertico Jersey Design with Unique Back Graphics' },
        { src: 'img/design/jersey/jersey (58).jpg', title: 'Custom VERTICO Team Fortress 2 Jersey Design with Desert Theme and Name Plate' },
        { src: 'img/design/jersey/jersey (59).jpg', title: 'Vertico Engineering Uniform with Power Plant Backdrop' },
        { src: 'img/design/jersey/jersey (60).jpg', title: 'Retro Jersey Design for Minic Team' },
        { src: 'img/design/jersey/jersey (61).jpg', title: 'Mens Basketball Jersey - Retro Collection' },
        { src: 'img/design/jersey/jersey (62).jpg', title: 'Vertigo Esports Retro Jersey Design' },
        { src: 'img/design/jersey/jersey (63).jpg', title: 'New Design: Retro Collection - Football Jersey' },
        { src: 'img/design/jersey/jersey (64).jpg', title: 'Vertigo Soccer Jersey Design with Graphic Text and Flame Elements' },
        { src: 'img/design/jersey/jersey (65).jpg', title: 'Vertigo Reversible Shirt - New Design - Retro Collection' },
        { src: 'img/design/jersey/jersey (66).jpg', title: 'Retro Coffee Shirt Design - Vertica' },
        { src: 'img/design/jersey/jersey (67).jpg', title: 'New Design for Verdict Retro Collab' },
        { src: 'img/design/jersey/jersey (68).jpg', title: 'NY Knicks Basketball Jersey Design' },
        { src: 'img/design/jersey/jersey (69).jpg', title: 'Pink and black retro sports jersey design by Sports Mania.' },
        { src: 'img/design/jersey/jersey (70).jpg', title: 'Jersey Design for Wedding Celebration Sports Theme' },
        { src: 'img/design/jersey/jersey (71).jpg', title: 'ILKS Sports Jersey Design' },
        { src: 'img/design/jersey/jersey (72).jpg', title: 'Poster for AEC3 on Leake Island Event.' },
        { src: 'img/design/jersey/jersey (73).jpg', title: 'Green and Red Football Jersey Design for Malaysia University Team' },
        { src: 'img/design/jersey/jersey (74).jpg', title: 'Sporting Team Jersey Displayed for Sniper Cj' },
        { src: 'img/design/jersey/jersey (75).jpg', title: 'Mens Track & Field Uniform Design by INJ and Z123 Sports Printing' },
        { src: 'img/design/jersey/jersey (76).jpg', title: 'Educational Sports Jersey Design' },
        { src: 'img/design/jersey/jersey (77).jpg', title: 'Menjerit Gaming Tournament Team Jersey' },
        { src: 'img/design/jersey/jersey (78).jpg', title: 'Promotional Image for Unikorn Gaming Team at an Innovation Event' },
        { src: 'img/design/jersey/jersey (79).jpg', title: 'Unified Tone Student Chapter Merchandise Display' },
        { src: 'img/design/jersey/jersey (80).jpg', title: 'Gaming Tournament Poster for Menjerit Event - Team Uniform Front and Back' },
        { src: 'img/design/jersey/jersey (81).jpg', title: 'MOT Club Jersey Sneak Peek for Gaming Tournament' },
        { src: 'img/design/jersey/jersey (82).jpg', title: 'Round Neck Version of MRT Club T-Shirt' },
        { src: 'img/design/jersey/jersey (83).jpg', title: 'MBOT Club Round Neck T-Shirt Design' },
        { src: 'img/design/jersey/jersey (84).jpg', title: 'Malaysia Royal Blue Roundneck Collar Long Sleeve Jersey Design' },
        { src: 'img/design/jersey/jersey (85).jpg', title: 'Zizz Brothers Sports Printing Jersey Design' },
        { src: 'img/design/jersey/jersey (86).jpg', title: 'Graphic Jersey Design for Gaming Tournament' },
        { src: 'img/design/jersey/jersey (87).jpg', title: 'Black Soccer Jersey Design for Creative Media Team' },
        { src: 'img/design/jersey/jersey (88).jpg', title: 'CRM Apparel Design for Creative Minds' },
        { src: 'img/design/jersey/jersey (89).jpg', title: 'GMJ Malaysia Front Design Camouflage Jersey' },
        { src: 'img/design/jersey/jersey (90).jpg', title: 'Fantasy Football Championship Uniform Concept' },
        { src: 'img/design/jersey/jersey (91).jpg', title: 'GMI Champion Jersey Display' },
        { src: 'img/design/jersey/jersey (92).jpg', title: 'Construction Themed Polo Shirt Design' },
        { src: 'img/design/jersey/jersey (93).jpg', title: 'Gaming Tournament Shirt - Team Blue Jerseys' },
        { src: 'img/design/jersey/jersey (94).jpg', title: 'HNJ Gaming Jersey Design Concept' },
        { src: 'img/design/jersey/jersey (95).jpg', title: 'Design for a truck racing drivers uniform.' },
    ],
    logotext: [
        { src: 'img/design/logo/cover.jpg', title: 'Malaysia Royal Sports Event Poster' },
        { src: 'img/design/logo/7.jpg', title: 'Global Running Event - Gemafit' },
        { src: 'img/design/logo/abudzar logo baru.png', title: 'Abudzard Gaming Logo' },
        { src: 'img/design/logo/abudzar LOGO.png', title: 'Yellow and Black Logo with Abu Dhabi Grand Prix 2022 Dates' },
        { src: 'img/design/logo/abudzar1.png', title: 'Menjerit Gaming Festival 2021 Event Poster' },
        { src: 'img/design/logo/ae231.png', title: 'Logo for Area 23 gaming event' },
        { src: 'img/design/logo/ae232.png', title: 'Gaming Tournament Logo for AXI' },
        { src: 'img/design/logo/animated picture white.jpg', title: 'Animated Picture Logo' },
        { src: 'img/design/logo/apparel.png', title: 'Omar Apparel - Made in Malaysia' },
        { src: 'img/design/logo/ATUSA1.PNG', title: 'Patriotic Badge with USA Symbol and Ribbon' },
        { src: 'img/design/logo/ATUSA15.png', title: 'American Wolf Pride Emblem' },
        { src: 'img/design/logo/barisan nasional.png', title: 'Poster for National Youth Day Celebration in Indonesia' },
        { src: 'img/design/logo/biotech1.jpg', title: 'Biotech University of Malaysia Logo' },
        { src: 'img/design/logo/biotech2.jpg', title: '2 DEDEK TECH' },
        { src: 'img/design/logo/biotech3.jpg', title: 'Biotec logo graphic design' },
        { src: 'img/design/logo/biotech5.jpg', title: '20 Years Anniversary Biotechnology Event Poster' },
        { src: 'img/design/logo/BLEAKANGCRM1.png', title: 'Abstract Collage Artwork' },
        { src: 'img/design/logo/CRM2 - FAIZ14.jpg', title: 'Mega Event Advertisement in Indonesian' },
        { src: 'img/design/logo/designbelakang.png', title: 'Malaysian Institute of Technology - Est. 1992 Flag' },
        { src: 'img/design/logo/gegau.png', title: 'Grey Overlay on Blurred Image' },
        { src: 'img/design/logo/germany.png', title: 'Germany Team Logo for Menjerit Event' },
        { src: 'img/design/logo/gm1.png', title: 'German Malaysian Institute Green Mover Logo' },
        { src: 'img/design/logo/gm2.png', title: 'Green leaf and speech bubble logo for GMI Green Move Initiative' },
        { src: 'img/design/logo/gm3.png', title: 'Green Movement Malaysian Institute Official Logo' },
        { src: 'img/design/logo/gm4.png', title: 'Green Mover Malaysian Institute Logo' },
        { src: 'img/design/logo/gm5.png', title: 'Green Mover GMI Logo' },
        { src: 'img/design/logo/gm6.png', title: 'Green Mover GMI Logo' },
        { src: 'img/design/logo/grafika4.png', title: 'Graphika - Freedom of Expression Logotype' },
        { src: 'img/design/logo/grafika6.png', title: 'Abstract Graphic Design Brand Logo' },
        { src: 'img/design/logo/grafika8.png', title: 'Graphica Logo with Lightning Bolt Design' },
        { src: 'img/design/logo/KPC LOGO.png', title: 'KPC Malaysia Official Logo' },
        { src: 'img/design/logo/l1.jpg', title: 'Penjipir Seni: Vintage Event Logo' },
        { src: 'img/design/logo/l2.jpg', title: 'Bahasa Indonesia Wordle Splash Graphic' },
        { src: 'img/design/logo/l3.jpg', title: 'Electric Charge Animatic Concept Design' },
        { src: 'img/design/logo/l4.jpg', title: 'Bright Blue Explosion Graphic with Text Overlay' },
        { src: 'img/design/logo/L5.jpg', title: 'Penghargaan Sesama Graphic Art' },
        { src: 'img/design/logo/L6.jpg', title: 'Metal Band Album Cover with Gothic Text and Faded Elements' },
        { src: 'img/design/logo/l7.jpg', title: 'Adobe Photoshop Icon and Text in Indonesian' },
        { src: 'img/design/logo/lega1.png', title: 'Stylish Gaming Tournament Logo for LeGea' },
        { src: 'img/design/logo/lega2.png', title: 'Red, Black & Blue Gaming Team Logo' },
        { src: 'img/design/logo/lega3.png', title: 'Bold White Text on Yellow Background' },
        { src: 'img/design/logo/lega4.png', title: 'GMI Gaming Team Logo' },
        { src: 'img/design/logo/lega5.png', title: 'GMI Gaming Logo in Black and Red' },
        { src: 'img/design/logo/lega6.png', title: 'GMI Legalese Logo' },
        { src: 'img/design/logo/lega7.png', title: 'LEGION BRANDING LOGO' },
        { src: 'img/design/logo/lega8.png', title: 'Legacy Media Club Logotype' },
        { src: 'img/design/logo/lega9.png', title: 'Legarians Unlimited Media Logo with Camera and Script Elements' },
        { src: 'img/design/logo/limited edition.jpg', title: 'LIMITED EDITION LOGO' },
        { src: 'img/design/logo/logo (1).jpg', title: 'Gaming Tournament Poster for Menjerit Event 1992' },
        { src: 'img/design/logo/logo (1).png', title: 'German Malaysia Institute Logo' },
        { src: 'img/design/logo/logo (2).jpg', title: 'Vans x Supreme Skateboard Collaboration Logotype' },
        { src: 'img/design/logo/logo (2).png', title: 'Menjerit Gaming Tournament 1992 Logo' },
        { src: 'img/design/logo/logo (3).jpg', title: 'Malaysia University Graphic Design' },
        { src: 'img/design/logo/logo (3).png', title: 'German Malaysian Institute Sports Logo' },
        { src: 'img/design/logo/logo (4).jpg', title: 'University Malaysia Logo' },
        { src: 'img/design/logo/logo (4).png', title: 'Final Chapter GMI Poster' },
        { src: 'img/design/logo/logo (5).jpg', title: 'H&H Construction Enterprise Logo' },
        { src: 'img/design/logo/logo (5).png', title: 'High Quality Sungai Angkas Jerseys Wanted' },
        { src: 'img/design/logo/logo (6).jpg', title: 'Construction Enterprise Logo' },
        { src: 'img/design/logo/logo (6).png', title: 'Handball Team Logo' },
        { src: 'img/design/logo/logo (7).jpg', title: 'Construction Company Logo - Hen Construction Enterprises' },
        { src: 'img/design/logo/logo (7).png', title: 'German Malaysian Institute Logo' },
        { src: 'img/design/logo/logo (8).jpg', title: 'Construction Enterprise Company Logo with Orange Crane and Horizon Sunrise' },
        { src: 'img/design/logo/logo (8).png', title: 'German-Malaysian Institute Poster.' },
        { src: 'img/design/logo/logo (9).jpg', title: 'Construction Enterprise Logo featuring Bulldozer' },
        { src: 'img/design/logo/logo (9).png', title: 'Logo 9 PNG' },
        { src: 'img/design/logo/logo (10).jpg', title: 'Logo 10' },
        { src: 'img/design/logo/logo (10).png', title: 'Gaming Tournament Poster for Royal Family University of Malaysia Legacy Event' },
        { src: 'img/design/logo/logo (11).jpg', title: 'Logo for Viking Gaming Team' },
        { src: 'img/design/logo/logo (11).png', title: 'Mountains and Clouds in Red and Black on White' },
        { src: 'img/design/logo/logo (12).jpg', title: 'Digital Art V Icon' },
        { src: 'img/design/logo/logo (12).png', title: 'Ban Smoking Graphic in Red and White' },
        { src: 'img/design/logo/logo (13).jpg', title: 'Gaming Tournament Logo for Valorant Event' },
        { src: 'img/design/logo/logo (13).png', title: 'Malaysian Institute of Engineering and Technology Est. 1992' },
        { src: 'img/design/logo/logo (14).jpg', title: 'Vans Logo in Black and White' },
        { src: 'img/design/logo/logo (14).png', title: 'Logo of Menjerit Event with Starburst Graphics' },
        { src: 'img/design/logo/logo (15).jpg', title: 'Logo for Menjerit Gaming Tournament featuring neon green and black design.' },
        { src: 'img/design/logo/logo (16).jpg', title: 'Neon Green Viking Logo on Black Background' },
        { src: 'img/design/logo/logo (17).jpg', title: 'Luxurious Logo of an Exclusive Brand' },
        { src: 'img/design/logo/logo (18).jpg', title: 'Run Meter Meter War Event Poster' },
        { src: 'img/design/logo/logo (19).jpg', title: 'University Malaysia Logo' },
        { src: 'img/design/logo/logo (20).jpg', title: 'M1M1 Gaming Team Logo' },
        { src: 'img/design/logo/logo (21).jpg', title: 'Brand Logo for UM Brand' },
        { src: 'img/design/logo/logo (22).jpg', title: 'University Malaysia Poster' },
        { src: 'img/design/logo/logo (23).jpg', title: 'University of Malaya Logo' },
        { src: 'img/design/logo/logo (24).jpg', title: 'Masked Blessing T-Shirt Design' },
        { src: 'img/design/logo/logo (25).jpg', title: 'Hauhsamoa - Established in 2019 - Graphic Design' },
        { src: 'img/design/logo/logo bawah.png', title: 'V.C. 90 Minutes Tackle Sticker' },
        { src: 'img/design/logo/logo crm3.png', title: 'Menjerit Gaming Tournament Logo' },
        { src: 'img/design/logo/logo gmi6.png', title: 'Green Mover Club Logo - Save, Feel, See!' },
        { src: 'img/design/logo/logo poknik.jpg', title: 'Abu Dhabi AD 2021/2022 Event Logo' },
        { src: 'img/design/logo/logo1(1).jpg', title: 'Sams Signature Burger Logo' },
        { src: 'img/design/logo/logo2(1).jpg', title: 'Sams Signature Burger Logo' },
        { src: 'img/design/logo/logo3(1).jpg', title: 'Sams Signature Burger Logo' },
        { src: 'img/design/logo/logo4(1).jpg', title: 'Burger Sams Signature Hamburger Logo' },
        { src: 'img/design/logo/logo5(1).jpg', title: 'Sams Signature Fresh and Tasty Logo' },
        { src: 'img/design/logo/logo6(1).jpg', title: 'Burger logo for Sams Signature Burger' },
        { src: 'img/design/logo/logoo.png', title: 'German Malaysian Institute Logo' },
        { src: 'img/design/logo/logoo3.jpg', title: 'German Malaysian Institute Logo' },
        { src: 'img/design/logo/LTD.png', title: 'LIMITED EDITION LOGO' },
        { src: 'img/design/logo/moksha.png', title: 'Red and White Flag Icon' },
        { src: 'img/design/logo/Myself Cover(1).png', title: 'Cranberry Juice Cartoon With Lemon' },
        { src: 'img/design/logo/Myself Cover.png', title: 'Cartoon Crate of Amino Acids, 100% Ahmad Faz Flavor' },
        { src: 'img/design/logo/NOW OR NEVER.png', title: 'Shredded Credit Card' },
        { src: 'img/design/logo/ONN DUTY ILLUSTRATION.png', title: 'Yellow Dump Truck On Duty and H&H Logo' },
        { src: 'img/design/logo/POSTER122.jpg', title: 'Penjelajahan Penuh Suka Ani Graphic Banner' },
        { src: 'img/design/logo/projek sawi.png', title: 'Logo for Project Sawi Event' },
        { src: 'img/design/logo/sma7.png', title: 'Logo of Indonesian Association for Islamic Studies with English and Arabic Inscriptions' },
        { src: 'img/design/logo/SPORTSCEINCE SEJAYA.jpg', title: 'Sport & Science Logo with Bold Typeface and Red Outline' },
        { src: 'img/design/logo/STICKER MOTO.png', title: 'Yellow Student Zone Sign for GMI German Malaysian Institute' },
        { src: 'img/design/logo/the grato.png', title: 'Futuristic Design Style Image with Abstract Elements' },
        { src: 'img/design/logo/unimalaya logo.png', title: 'University of Malaya Logo' },
        { src: 'img/design/logo/vc1.png', title: 'Menjelajahi Kesepuluh Daftar Kategori di IBU' },
        { src: 'img/design/logo/white logo.png', title: 'Gaming Tournament Poster for Menjerit Event' },
    ],
    customart: [
        { src: 'img/design/custom/cover.jpg', title: 'Sustainable Lifestyle Comic Book Cover Featuring Superheroes' },
        { src: 'img/design/custom/adult.png', title: 'Personalized Avatar Design with Physical Attributes' },
        { src: 'img/design/custom/aqil.png', title: 'Young politician addressing assembly with raised hand' },
        { src: 'img/design/custom/camera angle1 (draw).png', title: 'Gaming Tournament Schedule Featuring Various Game Genres' },
        { src: 'img/design/custom/camera angle2 (draw).png', title: 'Gaming Tournament Schedule and Map' },
        { src: 'img/design/custom/character1.png', title: 'Character Design for Mr. John Wick' },
        { src: 'img/design/custom/character2.png', title: 'Side Character Profile Illustration for Mr. Wilson' },
        { src: 'img/design/custom/character3.png', title: 'Side Character Mr. Aurelio, Age 28 Male Insurance Broker American Professional' },
        { src: 'img/design/custom/comic1.png', title: 'Video Editing Timeline Screenshots' },
        { src: 'img/design/custom/comic2.png', title: 'Videographers Candid Shots of People in Office' },
        { src: 'img/design/custom/custom (1).jpg', title: 'The Power of Living in the Present - Finding Joy in Life: A Workshop on Mindfulness and Happiness...' },
        { src: 'img/design/custom/custom (1).png', title: 'GMI Song Composition Contest Poster' },
        { src: 'img/design/custom/custom (2).jpg', title: 'Indonesian Propaganda Poster' },
        { src: 'img/design/custom/custom (2).png', title: '8-bit spaceship game graphic' },
        { src: 'img/design/custom/custom (3).jpg', title: 'Equal Opportunities for All Poster in Indonesian and English' },
        { src: 'img/design/custom/custom (3).png', title: 'Skull face graphic on mans photo' },
        { src: 'img/design/custom/custom (4).jpg', title: 'Illustration of a Man in Traditional Clothing' },
        { src: 'img/design/custom/custom (4).png', title: 'Cartoon Man with Sunglasses and Drips' },
        { src: 'img/design/custom/custom (5).jpg', title: 'Dinner Time - Whats for Dinner? Poster' },
        { src: 'img/design/custom/custom (6).jpg', title: 'I Code Model: Technical Instructors Training Approach' },
        { src: 'img/design/custom/custom (7).jpg', title: 'Abstract Arabic Calligraphy Design' },
        { src: 'img/design/custom/custom (8).jpg', title: 'Colorful Apartment Building with Alphabetical Letters on Windows' },
        { src: 'img/design/custom/custom (9).jpg', title: 'Man wearing yellow shirt looking at phone with drawn on face and drooling.' },
        { src: 'img/design/custom/d (1).jpeg', title: 'Simple Line Drawing of Chairs in an Assembly Hall' },
        { src: 'img/design/custom/d (1).png', title: 'Area of Triangle Formula Diagram' },
        { src: 'img/design/custom/d (2).png', title: 'Diagram of Compound Angles with Equations' },
        { src: 'img/design/custom/d (3).png', title: 'Sine Rule Demonstration with Angles and Sides Labeled' },
        { src: 'img/design/custom/d (4).png', title: 'Special Angles Diagram with Measurements' },
        { src: 'img/design/custom/d (5).png', title: 'Angles and Distance in Geometry Exercise' },
        { src: 'img/design/custom/d (6).png', title: 'Design Diagram with Circle and Cross' },
        { src: 'img/design/custom/d (7).png', title: 'Find the 2° Angle Diagram' },
        { src: 'img/design/custom/d (8).png', title: 'Poster Featuring Circular Symbol with Crosses and Colors' },
        { src: 'img/design/custom/d (9).png', title: 'Arc Length Calculation Equation Diagram' },
        { src: 'img/design/custom/d (10).png', title: 'Golf Club Head Diagram With Specs' },
        { src: 'img/design/custom/d (11).png', title: 'Circle with Area Measurements Diagram' },
        { src: 'img/design/custom/d (12).png', title: 'Nacho Cheese Tortilla Chips in Box' },
        { src: 'img/design/custom/d (13).png', title: 'Magic Circle Diagram with Dimensions in Meter' },
        { src: 'img/design/custom/d (14).png', title: 'Area of Sector Calculation Example' },
        { src: 'img/design/custom/d (15).png', title: 'Square Frame Image Showing a Circular Design with Diagonal Lines and Measurements' },
        { src: 'img/design/custom/d (16).png', title: 'Square Frame with Circular Design Inside' },
        { src: 'img/design/custom/d (17).png', title: 'Sacred Geometry Diagram with Triangles and Circle' },
        { src: 'img/design/custom/d (18).png', title: 'Diagram of Triangle with Area Calculation' },
        { src: 'img/design/custom/d (19).png', title: 'Diagram of an object with measurements in cm.' },
        { src: 'img/design/custom/d (20).png', title: 'Character Profile: Abd B Mustafa - Front and Back Views' },
        { src: 'img/design/custom/d (21).png', title: 'Illustrated Circuit Diagram' },
        { src: 'img/design/custom/d (22).png', title: 'Geometric Angle and Line Measurements Diagram' },
        { src: 'img/design/custom/d (23).png', title: 'Diagram of The Coefficient Rule from a Physics Textbook.' },
        { src: 'img/design/custom/d (24).png', title: 'Emotional Expression Icons for Facial Recognition Training' },
        { src: 'img/design/custom/d (25).png', title: 'Cartoon Facial Expression Chart: Happy to Angry' },
        { src: 'img/design/custom/d (26).png', title: 'Profile Illustration of Bainun Binati Harun' },
        { src: 'img/design/custom/d (27).png', title: 'Womans Profile Illustration with Color Palette' },
        { src: 'img/design/custom/d (28).png', title: 'House Area Math Problem Image' },
        { src: 'img/design/custom/d (29).png', title: 'Cartesian Coordinates Diagram with Quadrants' },
        { src: 'img/design/custom/d (30).png', title: 'Diagram of an Electron Transport Chain with Measurements in Micrometers' },
        { src: 'img/design/custom/d (31).png', title: 'Laser Angle and Distance Measurement Diagram' },
        { src: 'img/design/custom/d (32).png', title: 'Triangle Geometry Diagram and Angle Calculations' },
        { src: 'img/design/custom/d (33).png', title: 'Geometrical Diagram for Calculating Angle between Lines' },
        { src: 'img/design/custom/d (34).png', title: 'Trigonometry Angle and Side Relationships' },
        { src: 'img/design/custom/d (35).png', title: 'Diagram of Angle Calculation for Optical Setup' },
        { src: 'img/design/custom/d (36).png', title: 'Ping Pong Table With Red Ball Netting' },
        { src: 'img/design/custom/d (37).png', title: 'Laser Beam Angle Measurement Diagram' },
        { src: 'img/design/custom/d (38).png', title: 'Laser and Corner Angle Calculation Diagram' },
        { src: 'img/design/custom/d (39).png', title: 'Diagram of Laser Angle for Optical Table' },
        { src: 'img/design/custom/d (40).png', title: 'Geometry problem diagram for laser angle calculation' },
        { src: 'img/design/custom/d (41).png', title: 'Calculating Laser Angle for HD Optics.' },
        { src: 'img/design/custom/d (42).png', title: 'Pink triangle diagram with calculated angles' },
        { src: 'img/design/custom/d (43).png', title: 'Museum Exhibit Area Calculation Example Image' },
        { src: 'img/design/custom/d (44).png', title: 'Mechanical Design Blueprint for P Part' },
        { src: 'img/design/custom/d (45).png', title: 'House Elevation and Plan Diagram' },
        { src: 'img/design/custom/d (46).png', title: 'Calculating Volume of Museum Exhibit.' },
        { src: 'img/design/custom/d (47).png', title: 'Doorway Signage for Restroom Accessibility' },
        { src: 'img/design/custom/d (48).png', title: 'The Pink Elephant - A Boutique Retreat' },
        { src: 'img/design/custom/d (49).png', title: 'Metal Frame Construction Diagram with Dimensions' },
        { src: 'img/design/custom/d (50).png', title: 'Optical Prism Diagram With Angles and Equations' },
        { src: 'img/design/custom/e1.png', title: 'Cartoon Emotions Illustrated Series' },
        { src: 'img/design/custom/e2.png', title: '10 Emotional States - Cartoon Man Faces' },
        { src: 'img/design/custom/e3.png', title: 'Mans facial expressions labeled with different emotions.' },
        { src: 'img/design/custom/faris2.PNG', title: 'Man Riding Bicycle Loaded With Packages' },
        { src: 'img/design/custom/father emotions.png', title: 'Emotions of an Animated Character' },
        { src: 'img/design/custom/father old emotion.png', title: 'Emotion Illustrations of Mans Face with Descriptive Words' },
        { src: 'img/design/custom/father old.png', title: 'Character Design Sheet of Mustafa Bin Khan' },
        { src: 'img/design/custom/father.png', title: 'Illustration of Mustafa Bin Kahar in casual attire.' },
        { src: 'img/design/custom/gmi crm.png', title: 'Skeleton with fire powers character illustration.' },
        { src: 'img/design/custom/kid.png', title: 'Illustration of Two People in Different Styles with Background and Text Information' },
        { src: 'img/design/custom/man.png', title: 'Digital Character Concept Art - Abubakar Mustafa' },
        { src: 'img/design/custom/medicresearch (1).png', title: 'Ankle Fracture with Metal Screws' },
        { src: 'img/design/custom/medicresearch (2).png', title: 'Lip Enhancement Illustration with Implant Details' },
        { src: 'img/design/custom/medicresearch (3).png', title: 'Red lipstick on top of metal wires.' },
        { src: 'img/design/custom/medicresearch (4).png', title: 'Wrist Joint with Electronic Device for Pain Management' },
        { src: 'img/design/custom/medicresearch (5).png', title: 'Knee Joint Model with Bone Fracture and Stabilizing Screws' },
        { src: 'img/design/custom/medicresearch (6).png', title: 'Bone Fracture Internal Fixation' },
        { src: 'img/design/custom/mother old emotions.png', title: 'Emotional Expressions in Cartoon Style' },
        { src: 'img/design/custom/mother old.png', title: 'Illustration of Character Sheet with Name, Age, Height, and Ethnicity' },
        { src: 'img/design/custom/mother.png', title: 'Personal Profile Illustration: Baiun Binati Harun' },
        { src: 'img/design/custom/pulut1.jpg', title: 'Nike Dunk Low Sneaker Promotional Image' },
        { src: 'img/design/custom/robot view 2.png', title: 'R2D2 Robot with Jet Pack and Blaster from Star Wars.' },
        { src: 'img/design/custom/robot view 3.png', title: 'Robot designs for different functions and purposes.' },
        { src: 'img/design/custom/robot view front.png', title: 'Cute Cartoon Robot Image' },
        { src: 'img/design/custom/robot view side.png', title: 'Cartoon Drawing of a Vehicle' },
        { src: 'img/design/custom/robot view up.png', title: 'Robotic Arm Illustration in Black and White' },
        { src: 'img/design/custom/storyboard.png', title: 'Thumbnail for Thumbball Storyboard (6 Panels)' },
        { src: 'img/design/custom/teen.png', title: 'Character Design Sheet for Abdul Mustafa' },
        { src: 'img/design/custom/avatar/1.quai young.png', title: 'Brave Heroic Teenage Warrior Character Design' },
        { src: 'img/design/custom/avatar/2.Quai middle.png', title: 'Quad Middle - Anime Character Outfit Design Sheet' },
        { src: 'img/design/custom/avatar/3.Quai old.png', title: 'Quaid - Brave and Kind Character Design' },
        { src: 'img/design/custom/avatar/4.Azazil.png', title: 'Dual-color Azazil character design with red and black.' },
        { src: 'img/design/custom/avatar/5.Aroush.png', title: 'Sword & Skull Logo Design with Color Chart' },
        { src: 'img/design/custom/avatar/6.Leluhur.png', title: 'LELAHUR Character Design from Water, Earth, Air Neutral Nature' },
        { src: 'img/design/custom/avatar/air.png', title: 'Air Ninja Comic Cover Image' },
        { src: 'img/design/custom/avatar/blaze.png', title: 'Ninjutsu: Fire Release Mastery Training' },
        { src: 'img/design/custom/avatar/earth.png', title: 'Wizard in Robes with Earth Elemental' },
        { src: 'img/design/custom/avatar/fire.png', title: 'Woman performing martial art technique with fire.' },
        { src: 'img/design/custom/storyboard/storyboard1.png', title: 'Sleepy Mans Nighttime Tech Routine' },
        { src: 'img/design/custom/storyboard/storyboard2.png', title: 'Gamers Saga of Screen Time and Sleep Deprivation' },
        { src: 'img/design/custom/storyboard/storyboard3.png', title: 'Gaming Tournament Poster Featuring Four Players in Action' },
        { src: 'img/design/custom/storyboard/storyboard4.png', title: 'Crying Over Spilled Milk Comic Strip' },
        { src: 'img/design/custom/storyboard/storyboard5.png', title: 'Man on Phone Discussing with Another Person' },
        { src: 'img/design/custom/storyboard/storyboard6.png', title: 'Panel Comic - Man on Phone Ignores Surprise Party' },
    ],
    sticker: [
        { src: 'img/design/stickers/cover.jpg', title: 'Man holding money with Germany flag background' },
        { src: 'img/design/stickers/sticker jet1.png', title: 'Gold Glow Gathering Graphic Design' },
        { src: 'img/design/stickers/STICKER KRETA gold.png', title: 'Religious Event Invitation in Arabic' },
        { src: 'img/design/stickers/stickers (1).jpg', title: 'Free Gift Four Stickers GMI Suka Aduh' },
        { src: 'img/design/stickers/stickers (1).png', title: 'GMI 2021-2023 Accreditation Sticker' },
        { src: 'img/design/stickers/stickers (2).png', title: 'Student Union Election 2020 Candidate Badge' },
        { src: 'img/design/stickers/stickers (3).png', title: 'Managing Football in IBU' },
        { src: 'img/design/stickers/stickers (4).png', title: 'Friendly Match Poster - Aku Namai Laki - Jan 2023 - OWL Trafford - Team Colors' },
        { src: 'img/design/stickers/stickers (6).png', title: 'SEI 2021/2022 Event Pass' },
        { src: 'img/design/stickers/stickers (7).png', title: 'University of Malaya 2021/2023 ID Card' },
        { src: 'img/design/stickers/stickers (8).png', title: 'UPM SEMESTER 2022/2023 IDENTITY CARD' },
        { src: 'img/design/stickers/stickers (9).png', title: 'GMI Student Hostel Zone 2023-2024' },
        { src: 'img/design/stickers/stickers (10).jpg', title: 'Free Gift Sticker Pack Featuring Markahs Kissing Art' },
        { src: 'img/design/stickers/stickers (11).jpg', title: 'Free Gift Stickers No Parking Sign Sticker' },
        { src: 'img/design/stickers/stickers (12).jpg', title: 'Free Gift for Four Sticker - Pemain Air Mata Kucing Campaign Advertisement' },
        { src: 'img/design/stickers/stickers (13).jpg', title: 'Free Gift Sticker Fast & Furious Demikian Family Bumper Sticker' },
        { src: 'img/design/stickers/stickers (14).jpg', title: 'Sticker Giveaway Promotional Image' },
        { src: 'img/design/stickers/stickers (15).jpg', title: 'Free Sticker Poster for Menjerit Event' },
        { src: 'img/design/stickers/stickers (16).jpg', title: 'Engineering Study Encouragement Sticker' },
        { src: 'img/design/stickers/stickers (17).jpg', title: 'Anak Matak Free Gift Stickers Image' },
        { src: 'img/design/stickers/stickers (18).jpg', title: 'Plastic HEATM Poster with Caution Symbols' },
    ],
    products: [
        { src: 'img/design/product/cover.png', title: 'Project Today Special Oil Bottle Advertisement' },
        { src: 'img/design/product/5800894.png', title: 'Project Saw Signage' },
        { src: 'img/design/product/6239674.png', title: 'Giant Billboard Advertisement for Beverage Brand' },
        { src: 'img/design/product/business card back.png', title: 'Co-Founder Profile Card for Ahmad Fazli Faizal' },
        { src: 'img/design/product/business card front.png', title: 'Spicy Mustard Brand Identity Design' },
        { src: 'img/design/product/card1.png', title: 'Business Card of CEO & Founder Muhammad Naim from Jet Designs' },
        { src: 'img/design/product/card2.png', title: 'Logo for N1 Industry Creative Designer' },
        { src: 'img/design/product/card3.png', title: 'Wedding Design Contact Information' },
        { src: 'img/design/product/card4.png', title: 'Poster Featuring Artistic Design with Company Logo' },
        { src: 'img/design/product/card5.png', title: 'Jet Designs Brand Logo' },
        { src: 'img/design/product/card6.png', title: 'Biography Card for Muhammad Nashih bin Mohd Nasser' },
        { src: 'img/design/product/COVER1.png', title: 'Arabic Calligraphy Logo on a Geometric Design' },
        { src: 'img/design/product/cover2.jpg', title: 'School Signboard with Islamic Messages' },
        { src: 'img/design/product/COVER2.png', title: 'Golden Gilding on Black Background' },
        { src: 'img/design/product/cover3.jpg', title: 'Koleksi Foto Edisi Ke 54 - Koleksi Kekayaan Islam Sultana Ajaan' },
        { src: 'img/design/product/COVER3.png', title: 'Poster for Islamic Prayer Gathering with Arabic Text and Decoration' },
        { src: 'img/design/product/cover4.jpg', title: 'Green and Gold Islamic Religious Book Cover with Arabic Text' },
        { src: 'img/design/product/COVER4.png', title: 'Artificial Intelligence Neural Network Graphic' },
        { src: 'img/design/product/cover5.jpg', title: 'Book Cover: BENYAN WATAN in Arabic script, 54th edition' },
        { src: 'img/design/product/COVER5.png', title: 'Interactive Educational Program Poster' },
        { src: 'img/design/product/COVER6.png', title: 'Konferensi Islam Sukma Alam Shah' },
        { src: 'img/design/product/COVER7.png', title: 'Poster for Edisi Ke 54 Bincangan Wakaf Event in Indonesia' },
        { src: 'img/design/product/COVER8.png', title: 'Elegant Arabic Design Cover for Rajaz Maqam Booklet' },
        { src: 'img/design/product/COVER9.png', title: 'Memory album cover in Arabic script.' },
        { src: 'img/design/product/coverfilter.png', title: 'Koleksi Islam Sultanul Ahmadi Poster Series #54' },
        { src: 'img/design/product/food sticker.png', title: 'Frozen Fish Head Curry Menu Poster' },
        { src: 'img/design/product/kisas.jpg', title: 'Kisas High School: A Colorful Celebration of Culture and Learning' },
        { src: 'img/design/product/KULIT2.png', title: 'Koleksi Jilbab Islami Sultanul Ulama Syah' },
        { src: 'img/design/product/Logo_Mockup_070.png', title: 'PROJEKT SAWI Business Card with Leaf Design' },
        { src: 'img/design/product/packaging2.png', title: 'Peanut Butter Cookie Dough Packaging' },
        { src: 'img/design/product/packaging3.png', title: 'Yellow Mustard Packaging' },
        { src: 'img/design/product/packaging4.png', title: 'Project SAMI Nutrition Facts Label' },
        { src: 'img/design/product/Pickel.png', title: 'Glass jar of mustard pickle.' },
        { src: 'img/design/product/poster4x.PNG', title: 'Healthy Cooking Slogan Poster' },
        { src: 'img/design/product/powder.png', title: 'Nutrifood Projek Sawi Mixed Vegetable Powder Sachet' },
        { src: 'img/design/product/projek sawi.png', title: 'The image you sent appears to be an abstract or blurry graphic with no discernible content. There...' },
        { src: 'img/design/product/sauce.png', title: 'Mustard Seed Oil Extra Virgin Label Design' },
        { src: 'img/design/product/seeds.png', title: 'Seed Supplement Product Packaging' },
        { src: 'img/design/product/signboard1.png', title: 'Mandarin Mixed Rice Advertisement on Street Sign' },
        { src: 'img/design/product/sticker1.png', title: 'Project Mustard Powder Package with Vitamin C and Iron' },
        { src: 'img/design/product/top.png', title: 'Project Logo with Leaf and Wordmark' },
        { src: 'img/design/product/yellow mustard.png', title: 'Yellow mustard bottle with label.' },
    ],
    mcletter: [
        { src: 'img/design/mc/cover.jpg', title: 'Clinic Registration Form in Indonesian' },
        { src: 'img/design/mc/mc (1).jpg', title: 'UPJ Student ID Card' },
        { src: 'img/design/mc/mc (2).jpg', title: 'Poliklinik An Nur Receipt Form in Indonesian' },
        { src: 'img/design/mc/mc (3).jpg', title: 'Medical Certificate for Employee at Poliklinik An Nur.' },
        { src: 'img/design/mc/mc (4).jpg', title: 'Malaysian Hospital Administration Memo' },
    ],
    others: [
        { src: 'img/design/others/cover.jpg', title: 'Flame Design on Baseball Cap' },
        { src: 'img/design/others/barangpost2.jpg', title: 'Fashion Campaign for Customized Jackets' },
        { src: 'img/design/others/others (1).jpg', title: 'Gildan Cap Promotional Image for University of Malaysia Event' },
        { src: 'img/design/others/others (2).jpg', title: 'Gildan Cap Promo for University of Malaya with Contact Information' },
        { src: 'img/design/others/others (3).jpg', title: 'University Malaysia Gildan Cap Promotion' },
        { src: 'img/design/others/others (4).jpg', title: 'University Malaysia Gildan Hat Display' },
        { src: 'img/design/others/others (5).jpg', title: 'Gildan Cap Image Featuring University Malaysia Logo' },
        { src: 'img/design/others/others (6).jpg', title: 'University of Malaysia Gildan Cap Promotion' },
        { src: 'img/design/others/others (7).jpg', title: 'Malaysia 1957 Menswear Collection Poster' },
        { src: 'img/design/others/others (8).jpg', title: 'Man in navy blue jacket posing for photo.' },
        { src: 'img/design/others/others (9).jpg', title: 'Gaming Merit Varsity Poster with Person in Uniform' },
        { src: 'img/design/others/poster.jpg', title: 'White Athletics Jersey with Team Logo and Sponsor Details' },
        { src: 'img/design/others/poster1.jpg', title: 'Dragons and Skulls Jacket Design' },
    ],
    banner: [
        { src: 'img/design/banner/cover.jpg', title: 'Excellent Profits RM800 Winning Reward Poster' },
        { src: 'img/design/banner/banner (1).jpg', title: 'Sams Burger Co. - AYAM DAGING SANDWICH Advertisement' },
        { src: 'img/design/banner/banner (1).png', title: 'Children of the Future Event Flyer' },
        { src: 'img/design/banner/banner (2).jpg', title: 'Sams Burger Advertisement with Graphic Design and Promotional Message.' },
        { src: 'img/design/banner/banner (3).jpg', title: 'Sandwich Advertisement with Ayam Daging Promotion' },
        { src: 'img/design/banner/banner (4).jpg', title: 'Hamburger Flavor Variety Sign with Meat Types' },
        { src: 'img/design/banner/banner (5).jpg', title: 'Poster for Art Showcase and National Game Launch Event' },
        { src: 'img/design/banner/banner (6).jpg', title: 'Artist Showcase Invitation Poster - Malaysia' },
        { src: 'img/design/banner/banner (7).jpg', title: 'Excellent Profits Advertising Banner' },
        { src: 'img/design/banner/banner (8).jpg', title: 'Directional Sign for Excellent Prints' },
        { src: 'img/design/banner/banner (9).jpg', title: 'Excellent Profits Event Sign' },
        { src: 'img/design/banner/banner (10).jpg', title: 'Event Promotion for Hive MRT Station with a clear THIS WAY arrow and date range from 27th to 30th...' },
    ],
    nft: [
        { src: 'img/design/nft/cover.png', title: 'Pirate Monkey in Blue Uniform' },
        { src: 'img/design/nft/nft (1).png', title: 'person standing with a smile.' },
        { src: 'img/design/nft/nft (2).png', title: 'Anime Character in Purple Shirt' },
        { src: 'img/design/nft/nft (3).png', title: 'Cartoon Character in a Red T-Shirt Smiling' },
        { src: 'img/design/nft/nft (4).png', title: 'Smiling man in suit with red bowtie.' },
        { src: 'img/design/nft/nft (5).png', title: 'Cartoon Man in Polo Shirt Smiling' },
        { src: 'img/design/nft/nft (6).png', title: 'Man Standing in Black Shirt' },
        { src: 'img/design/nft/nft (7).png', title: 'Casual Businessman Character Illustration in Purple' },
        { src: 'img/design/nft/nft (8).png', title: 'Cartoon Cowboy Character Illustration' },
        { src: 'img/design/nft/nft (9).png', title: 'Flame Skull in Chains Illustrated Design' },
        { src: 'img/design/nft/nft (10).png', title: 'Knight in Sneaky Ninjasuit' },
        { src: 'img/design/nft/nft (11).png', title: 'Determined Samurai in Battle' },
        { src: 'img/design/nft/nft (12).png', title: 'Crying Video Game Character Cartoon' },
        { src: 'img/design/nft/nft (13).png', title: 'Skeleton in Suit and Bowtie' },
        { src: 'img/design/nft/nft (14).png', title: 'Cartoon of a smiling man in a purple jacket.' },
        { src: 'img/design/nft/nft (15).png', title: 'Police Officer in Full Gear' },
        { src: 'img/design/nft/nft (16).png', title: 'SWAT Officer Illustrated Comic Style' },
        { src: 'img/design/nft/nft (17).png', title: 'Red Robot Standing with Smile' },
        { src: 'img/design/nft/nft (18).png', title: 'Masked Figure in a Cloak' },
        { src: 'img/design/nft/nft (19).png', title: 'Demonic Character with Red Eyes and Horned Goggles' },
        { src: 'img/design/nft/nft (20).png', title: 'Stylish Animated Character in Hoodie' },
        { src: 'img/design/nft/nft (21).png', title: 'Rapper Style Character Illustration' },
        { src: 'img/design/nft/nft (22).png', title: 'Stylish Person Wearing Sunglasses and a Chain' },
        { src: 'img/design/nft/nft (23).png', title: 'Sick Day Cartoon with Character Vomiting' },
        { src: 'img/design/nft/nft (24).png', title: 'Mummified Hero in Cloak' },
        { src: 'img/design/nft/nft (25).png', title: 'Helmeted Warrior in Blue Armor and Mask' },
        { src: 'img/design/nft/nft (26).png', title: 'Stormtrooper in gas mask with blaster rifle.' },
        { src: 'img/design/nft/nft (27).png', title: 'Dark Lord of Sith - Darth Vader' },
        { src: 'img/design/nft/nft (28).png', title: 'Armored Stormtrooper in Helmet' },
        { src: 'img/design/nft/nft (29).png', title: 'Skull in astronaut suit on purple background' },
        { src: 'img/design/nft/nft (30).png', title: 'Man in Red Suit and Dark Glasses' },
        { src: 'img/design/nft/nft (31).png', title: 'The image shows an animated character with a large head and a small body. The character has pale ...' },
        { src: 'img/design/nft/nft (32).png', title: 'Purple Thanos Staring Angrily' },
        { src: 'img/design/nft/nft (33).png', title: 'Gaming Streamer With Headphones and Mask' },
    ],
    photography: [
        { src: 'img/design/photography/cover.jpg', title: 'Group of Smiling People in Formal Wear' },
        { src: 'img/design/photography/1.jpg', title: 'Man in traditional Balinese attire.' },
        { src: 'img/design/photography/2.png', title: 'Man Sitting in Purple Top and Traditional Skirt' },
        { src: 'img/design/photography/3.jpg', title: 'Young man in casual streetwear.' },
        { src: 'img/design/photography/4.JPG', title: 'Man in Jeep Sweatshirt Posing' },
        { src: 'img/design/photography/5.jpg', title: 'Man holding a certificate.' },
        { src: 'img/design/photography/6.PNG', title: 'Malaysian Flag Raised on Wet Land' },
        { src: 'img/design/photography/7.png', title: 'Man with blood on face and hands.' },
        { src: 'img/design/photography/8.png', title: 'Man in hoodie talking on phone' },
        { src: 'img/design/photography/9.png', title: 'Men in jerseys posing for picture' },
        { src: 'img/design/photography/10.png', title: 'Man on bike carrying boxes' },
        { src: 'img/design/photography/m1.jpg', title: 'Photography tagline for Ahamd Faiz' },
        { src: 'img/design/photography/m2.jpg', title: 'QR code on wave image.' },
        { src: 'img/design/photography/m3.jpg', title: 'Product Advertisement featuring Energy Drink Bottle on Rock by Stream.' },
        { src: 'img/design/photography/m4.jpg', title: 'Fashion Inspiration Montage for Streetwear' },
        { src: 'img/design/photography/m5.jpg', title: 'Mascot Promotional Image with QR Code' },
        { src: 'img/design/photography/m5.PNG', title: 'Spices and Herbs on Table for Cooking' },
        { src: 'img/design/photography/m6.jpg', title: 'Lighted Minimalist Art in Office Tower' },
        { src: 'img/design/photography/m7.jpg', title: 'Street Art Mural with Graffiti and Messages' },
        { src: 'img/design/photography/m8.jpg', title: 'Toys on Display at Art Exhibition' },
        { src: 'img/design/photography/m9.jpg', title: 'Motorcycle Riding on Highways during Light Trial' },
        { src: 'img/design/photography/m10.jpg', title: 'Reflection of Man on Wet Street' },
        { src: 'img/design/photography/m11.jpg', title: 'SILHOUETTE: A Man in Profile and Palm Trees against a Sky Illustration.' },
        { src: 'img/design/photography/m12.jpg', title: 'Candid Image of Two Men Side by Side' },
        { src: 'img/design/photography/m13.jpg', title: 'Architecture Collage Featuring Storz Building and Cathedral Notre Dame' },
        { src: 'img/design/photography/m14.jpg', title: 'Street Life Mosaic: City Scene' },
        { src: 'img/design/photography/m15.jpg', title: 'Chicken Sandwich and Fries with FOOD Text' },
        { src: 'img/design/photography/m16.jpg', title: 'Landscape and Duck Triple Panel Image' },
        { src: 'img/design/photography/m17.jpg', title: 'Two people social distancing in an office.' },
        { src: 'img/design/photography/m18.jpg', title: 'Hands holding hand sanitizer labeled COVID-19.' },
        { src: 'img/design/photography/m19.jpg', title: 'Cosmetic display featuring lipsticks and eyeshadows.' },
        { src: 'img/design/photography/m20.jpg', title: 'Colorful Pencils in a Tin Can' },
        { src: 'img/design/photography/m21.jpg', title: 'Students Day Out: Library and Store Adventures' },
        { src: 'img/design/photography/m22.jpg', title: 'Spices Smeared on a Black Background' },
        { src: 'img/design/photography/m23.PNG', title: 'Stained Glass Shards on Blue Surface' },
        { src: 'img/design/photography/m24.PNG', title: 'Herb and Spice Apothecary Collection' },
        { src: 'img/design/photography/m25.PNG', title: 'Herbs in glass bottles on table.' },
        { src: 'img/design/photography/m26.PNG', title: 'Spice collection on black surface.' },
        { src: 'img/design/photography/m27.PNG', title: 'Spice Collection on White Surface' },
        { src: 'img/design/photography/p1.jpg', title: 'Martial Arts Training in Forest Environment' },
        { src: 'img/design/photography/p2.jpg', title: 'Man in green shirt slapping another mans shoulder.' },
        { src: 'img/design/photography/p3.jpg', title: 'Men engaged in martial arts training.' },
        { src: 'img/design/photography/p4.jpg', title: 'Two men practicing martial arts in an outdoor setting.' },
        { src: 'img/design/photography/p5.jpg', title: 'Two men interacting with an object' },
        { src: 'img/design/photography/p6.jpg', title: 'Man in chef attire and another man giving thumbs up.' },
        { src: 'img/design/photography/p7.jpg', title: 'Two men proudly holding a large fish.' },
        { src: 'img/design/photography/p8.jpg', title: 'Man pointing and smiling at camera, another man with sunglasses in background.' },
        { src: 'img/design/photography/p9.jpg', title: 'Two Men in Car, One Driving.' },
        { src: 'img/design/photography/p10.jpg', title: 'Young Men Driving Car Together' },
        { src: 'img/design/photography/p11.jpg', title: 'Two men sharing a moment of prayer on stairs' },
    ],
    socialmedia: [
        { src: 'img/design/socialmedia/cover.jpg', title: 'Operation Hour Poster Featuring Anime Character' },
        { src: 'img/design/socialmedia/fb1.jpg', title: 'Customer Feedback Example in a Chat Application' },
        { src: 'img/design/socialmedia/fb2.jpg', title: 'Customer Feedback Conversation Example' },
        { src: 'img/design/socialmedia/fb3.jpg', title: 'Customer Positive Feedback on Social Media' },
        { src: 'img/design/socialmedia/fb4.jpg', title: 'Positive Customer Feedback Chat Screenshot' },
        { src: 'img/design/socialmedia/fb5.jpg', title: 'Customer Feedback Example - Positive Support Exchange' },
        { src: 'img/design/socialmedia/fb6.jpg', title: 'Customer Feedback Message in Indonesian' },
        { src: 'img/design/socialmedia/fb7.jpg', title: 'Customer Feedback Screenshot with Response' },
        { src: 'img/design/socialmedia/fb8.jpg', title: 'Customer Feedback Message on Social Media Platform' },
        { src: 'img/design/socialmedia/fb9.jpg', title: 'Customer Feedback Screenshot' },
        { src: 'img/design/socialmedia/fb10.jpg', title: 'Customer Feedback Screenshot' },
        { src: 'img/design/socialmedia/INTERNSHIP 25.jpg', title: 'Set Realistic Expectations for Success' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS1.jpg', title: 'Internship Tips Advertisement - Be Brave, Be Limitless' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS2.jpg', title: 'Career Research Guidance Infographic' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS3.jpg', title: 'How to Prepare Resume and Cover Letter Infographic' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS4.jpg', title: 'Social Media Strategy Infographic' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS5.jpg', title: 'Step 4 Application Submit Guideline Graphic' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS6.jpg', title: 'Follow Up Email Etiquette Tips Chart' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS7.jpg', title: 'Interview Preparation Infographic by VERTICA' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS8.jpg', title: 'Internship Flexibility Graphic' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS9.jpg', title: 'Cartoon Job Hunting Advice Poster' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS10.jpg', title: 'Study Last Minute Tips Poster - Be Brave Be Limitless' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS11.jpg', title: 'Quick Study Plan with Timeline and Tip Bullet Points' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS12.jpg', title: 'Create Visual Ads - Mind Maps, Diagrams, Flashcards - Info Recollection Support' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS13.jpg', title: 'Active Learning Techniques Graphic' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS14.jpg', title: 'Memorize With Mnemonics and Acronyms Graphic' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS15.jpg', title: '5. Stay Hydrated and Take Breaks' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS16.jpg', title: 'Study Tips Poster: Eliminate Distractions and Enhance Focus' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS17.jpg', title: 'Smiling Emoji with Positive Thinking Reminder.' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS18.jpg', title: 'Review Notes and Memory Refreshment Tips Illustration' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS19.jpg', title: 'How to Use Online Resources for Learning' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS20.jpg', title: 'Tips Jadi Productive Poster with Slogan Be Brave Be Limitless' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS21.jpg', title: 'Setting Goals Infographic' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS22.jpg', title: 'Develop Schedule & Prioritize Tasks Infographic' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS23.jpg', title: 'Breakdown of Study Sessions Graphic' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS24.jpg', title: 'Educational Infographic on Active Learning Method' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS25.jpg', title: 'Set Realistic Expectations Graphic' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS26.jpg', title: 'Stay Organized - Study Tips Graphic' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS27.jpg', title: 'Develop Healthy Habits Advice Graphic' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS28.jpg', title: 'Girl Looking at Mirror Reflection Image' },
        { src: 'img/design/socialmedia/ORDER.jpg', title: '7 Step Order Process Infographic' },
        { src: 'img/design/socialmedia/poster cuti.jpg', title: 'Vertico Ramadan Campaign Poster Featuring Jersey Designs' },
        { src: 'img/design/socialmedia/POSTER MENJERIT GAMING1.jpg', title: 'E-Sports Gaming Tournament Poster for MENJERIT Event' },
        { src: 'img/design/socialmedia/POSTER MENJERIT MERDEKA3.jpg', title: 'Menjerit Sports Jersey Design for Mercedez Team' },
        { src: 'img/design/socialmedia/poster pilihanraya1.jpg', title: 'Parliament Malaysia 2023: Mohamad Fahmi Fazli Bin Mansor Campaign Poster' },
        { src: 'img/design/socialmedia/poster pilihanraya2.jpg', title: 'Malaysia Election Campaign Ad with Muslim Mans Face' },
        { src: 'img/design/socialmedia/poster pilihanraya3.jpg', title: 'Mohamed Rasdan, KBS Malaysia 2023 Event Promo' },
        { src: 'img/design/socialmedia/POSTERPROMO.jpg', title: 'Free Design Charge Event Poster for February' },
        { src: 'img/design/socialmedia/POSTERPROMOKOLARPOST.jpg', title: 'Futsal Jersey Promotion: Red, Black & Gold, Long Sleeves, Phoenix Design' },
        { src: 'img/design/socialmedia/POSTERPROMOKOLAR2POST.jpg', title: 'Promotional Football Jerseys with Phoenix Design for Limited Sale' },
        { src: 'img/design/socialmedia/POSTERPROMOKOLAR3POST.jpg', title: 'Polo Shirt Design Advertisement with Free Collar' },
        { src: 'img/design/socialmedia/POSTERPROMOKOLAR4POST.jpg', title: 'Promo Perumah Polo Kolar & Long Sleeve Khas untuk Wajar u/m' },
        { src: 'img/design/socialmedia/PRINT FLYERS A5 (6).png', title: 'Creative Design Services Advertisement' },
        { src: 'img/design/socialmedia/r1.png', title: 'Race Event Promotion Poster Featuring Sponsors Logos' },
        { src: 'img/design/socialmedia/r2.png', title: 'Running Edition Event Poster' },
        { src: 'img/design/socialmedia/r3.png', title: 'Pelatihan Penggunaan Material - Fun Run Uniform Design' },
        { src: 'img/design/socialmedia/r4.png', title: 'Poster for Healthtech Event Minimum Order Five Helai Sahaja' },
        { src: 'img/design/socialmedia/r5.png', title: 'Vertigo Neon Run Event T-Shirt Designs' },
        { src: 'img/design/socialmedia/r6.png', title: 'VECTICO Running Club Jersey Collection with Colorful Design and Boleh Tukar Warna Text Tag' },
        { src: 'img/design/socialmedia/SIZECHART1.jpg', title: 'Agent Vertigo 2014 Price List' },
        { src: 'img/design/socialmedia/SIZECHARTKIDS2.jpg', title: 'Size Chart for Kids Apparel' },
        { src: 'img/design/socialmedia/SIZECHARTMAN2.jpg', title: 'Vertigo Size Chart Poster' },
        { src: 'img/design/socialmedia/SIZECHARTMAN3.jpg', title: 'Vegetto Size Chart' },
        { src: 'img/design/socialmedia/SIZECHARTMUSLIMAH2.jpg', title: 'Mens Muslim Clothing Size Chart' },
        { src: 'img/design/socialmedia/SIZECHARTVARSITY.jpg', title: 'Jacket Varsity Size Chart' },
        { src: 'img/design/socialmedia/SOFT POSTER2.jpg', title: 'Green Energy Promotional Sign in Indonesian' },
        { src: 'img/design/socialmedia/softpoester3.jpg', title: 'No Plastic Team Pledge and Action Checklist Poster' },
        { src: 'img/design/socialmedia/STUDENT DEALS.jpg', title: '2021 Student Deals - Promo Pricing for Helai Short Sleeve' },
        { src: 'img/design/socialmedia/STUDENT DEALS3.jpg', title: 'Student Deals 2024 Poster - Free Custom Design - Round Neck Short Sleeve T-Shirt' },
        { src: 'img/design/socialmedia/SUCCESSTORYROZAIRI.jpg', title: 'Rozaimis Success - $109,975 Earned in Menjerit Event with 308 Cups Won by Joe Senban Team' },
        { src: 'img/design/socialmedia/thumbnail2.jpg', title: 'Tipster Video Featuring Indian Man' },
        { src: 'img/design/socialmedia/UCAPAN RAYA10.jpg', title: 'Eid Al-Fitr Greeting Card with Man and Woman in Traditional Attire' },
    ],
};