const galleryData = {
    poster: [
        { src: 'img/design/poster/cover.png', title: 'Flaming Skeletal Hand Holding Fire' },
        { src: 'img/design/poster/cdcoverfront.png', title: 'Poster for Children of the Future Program' },
        { src: 'img/design/poster/MEGAZINE COVER PBL2.png', title: 'The Extraordinary Juan Jabal' },
        { src: 'img/design/poster/p.jpg', title: 'Plastic Bags Advertisement' },
        { src: 'img/design/poster/p (1).jpg', title: 'Advertisement for Rice and Fried Chicken Promotion' },
        { src: 'img/design/poster/p (2).jpg', title: 'Food Promotion Poster' },
        { src: 'img/design/poster/p (3).jpg', title: 'Promotion for Rice Dish Sale with Set Meal Deal' },
        { src: 'img/design/poster/p (4).jpg', title: 'Promotional Advertisement for Food Delivery Service' },
        { src: 'img/design/poster/p (5).jpg', title: 'Plastic Surgery Clinic Advertisement' },
        { src: 'img/design/poster/p (6).jpg', title: 'Set Meal Promotion for Rice and Beef in Plastic Container' },
        { src: 'img/design/poster/palestineproject6.png', title: 'The image depicts a large crowd of people gathered on what appears to be a rooftop during either ...' },
        { src: 'img/design/poster/panglimas.png', title: 'Poster for Dragon Force eSports Team' },
        { src: 'img/design/poster/plastik.jpg', title: 'Indonesian Food Promotion Poster' },
        { src: 'img/design/poster/poster (1).jpg', title: 'Album Release Poster for Abubabah' },
        { src: 'img/design/poster/poster (1).png', title: 'Pile of Sneakers with Dragon Box in Center' },
        { src: 'img/design/poster/poster (2).jpg', title: 'LABIO Product Display' },
        { src: 'img/design/poster/poster (2).png', title: 'Plastic truck with branding.' },
        { src: 'img/design/poster/poster (3).jpg', title: 'Skadials Mobile Organizers' },
        { src: 'img/design/poster/poster (3).png', title: 'ABU GMI Poster.' },
        { src: 'img/design/poster/poster (4).jpg', title: 'Skadicals 3D printed objects' },
        { src: 'img/design/poster/poster (4).png', title: 'ABI Cartoon Movie Poster' },
        { src: 'img/design/poster/poster (5).jpg', title: 'Skateboarders personalized gear ad' },
        { src: 'img/design/poster/poster (5).png', title: 'ABU Movie Poster' },
        { src: 'img/design/poster/poster (6).jpg', title: 'Nurturing Culture and Empowering Minds Poster' },
        { src: 'img/design/poster/poster (6).png', title: 'Animated Movie Poster for ABU' },
        { src: 'img/design/poster/poster (7).jpg', title: 'Cheese Snack Advertisement' },
        { src: 'img/design/poster/poster (7).png', title: 'Animated film poster: Abu' },
        { src: 'img/design/poster/poster (8).jpg', title: 'Call for Food Sponsors Poster' },
        { src: 'img/design/poster/poster (8).png', title: 'Skeletal pirate in attire, holding skulls, grinning skeletally.' },
        { src: 'img/design/poster/poster (9).jpg', title: 'Graphika Logo and Design.' },
        { src: 'img/design/poster/poster (9).png', title: 'Costume of Grim Reaper holding a trumpet' },
        { src: 'img/design/poster/poster (10).png', title: 'Zombie Soldier Poster' },
        { src: 'img/design/poster/poster (11).png', title: 'Zombie-like figure in vibrant clothing.' },
        { src: 'img/design/poster/poster (12).png', title: 'Man in hoodie with face painted to look like a skull' },
        { src: 'img/design/poster/poster (13).PNG', title: 'International Leaders Mosaic' },
        { src: 'img/design/poster/poster (14).png', title: 'Do It Advertisement for Nike featuring an athlete in a space setting.' },
        { src: 'img/design/poster/poster (15).png', title: 'The Politics of Punching (Poster)' },
        { src: 'img/design/poster/poster (16).PNG', title: 'Urban Crime Scene Painting' },
        { src: 'img/design/poster/poster (17).PNG', title: 'Superheroes in Library Reading Books' },
        { src: 'img/design/poster/poster (18).png', title: 'Boy Reading Amidst Towering Pile of Books' },
        { src: 'img/design/poster/poster (19).PNG', title: 'Children in War-Torn City' },
        { src: 'img/design/poster/poster (20).PNG', title: 'Ritornare Delle Tue Ginocchia, Menjerit Tournament Poster' },
        { src: 'img/design/poster/poster (21).PNG', title: 'People of Malaysia National Day Poster' },
        { src: 'img/design/poster/POSTER.jpg', title: 'Poster for Multimedia Art Showcase in Malaysia' },
        { src: 'img/design/poster/poster.png', title: 'Woman on Magazine Cover with Smiling Face.' },
        { src: 'img/design/poster/poster5.png', title: 'Graphic Design Poster for Menjerit Kuala Lumpur' },
        { src: 'img/design/poster/poster6.png', title: 'Graphic Design Poster for Album Cover' },
        { src: 'img/design/poster/POSTERV5.png', title: 'Children of the Future Kids Carnival Flyer' },
        { src: 'img/design/poster/shame.PNG', title: 'Israelis Being Shot' },
        { src: 'img/design/poster/watermerdeka4-6.png', title: 'Man in river holding flags of Malaysia and USA.' },
    ],
    jersey: [
        { src: 'img/design/jersey/cover.jpg', title: 'Malaysia Royal FC Jersey Design' },
        { src: 'img/design/jersey/jersey.jpg', title: 'Red Jersey for American Athletics Team' },
        { src: 'img/design/jersey/jersey (1).jpg', title: 'Custom Hockey Jersey with Team Branding' },
        { src: 'img/design/jersey/jersey (1).png', title: 'University of Malaya Limited Edition Jersey' },
        { src: 'img/design/jersey/jersey (2).jpg', title: 'VERITCO 1 JERSEY SET' },
        { src: 'img/design/jersey/jersey (2).png', title: 'Black Camouflage Jersey Design' },
        { src: 'img/design/jersey/jersey (3).jpg', title: 'Veritco Team Jersey - Custom Design' },
        { src: 'img/design/jersey/jersey (3).png', title: 'Short Sleeve Soccer Jersey with Red and Black Design' },
        { src: 'img/design/jersey/jersey (4).jpg', title: 'Two Football Jerseys in Orange and White for Team VERITICO' },
        { src: 'img/design/jersey/jersey (4).png', title: 'Backpack Featuring NBA Team Jersey Design and QR Code' },
        { src: 'img/design/jersey/jersey (5).jpg', title: 'Veritco Jersey Set for Football Team' },
        { src: 'img/design/jersey/jersey (6).jpg', title: 'Vertico Jersey' },
        { src: 'img/design/jersey/jersey (7).jpg', title: 'Vertico Hockey Jersey' },
        { src: 'img/design/jersey/jersey (8).jpg', title: 'Vertico Football Jersey with Custom Design' },
        { src: 'img/design/jersey/jersey (9).jpg', title: 'Veritco Branded Jersey' },
        { src: 'img/design/jersey/jersey (10).jpg', title: 'A Veritico Jersey Set' },
        { src: 'img/design/jersey/jersey (11).jpg', title: 'Pink and White Verteco Jersey with Number 21' },
        { src: 'img/design/jersey/jersey (12).jpg', title: 'Vertico Jersey Set' },
        { src: 'img/design/jersey/jersey (13).jpg', title: 'Veritico 7 Jersey Display' },
        { src: 'img/design/jersey/jersey (14).jpg', title: 'Limited Edition Verteco NFT Football Jersey' },
        { src: 'img/design/jersey/jersey (15).jpg', title: 'Veritco Jersey Set with Custom Name and Logo' },
        { src: 'img/design/jersey/jersey (16).jpg', title: 'Custom Soccer Jersey by Vertico' },
        { src: 'img/design/jersey/jersey (17).jpg', title: 'Veritco. Racing Team Uniform' },
        { src: 'img/design/jersey/jersey (18).jpg', title: 'NHL Jersey Design with Custom Numbering' },
        { src: 'img/design/jersey/jersey (19).jpg', title: 'Silver New Zealand All Blacks Jersey with Black Limited 24 Design' },
        { src: 'img/design/jersey/jersey (20).jpg', title: 'Veritco Uniform Jersey Set' },
        { src: 'img/design/jersey/jersey (21).jpg', title: 'Blue and White Vertico Custom Jersey' },
        { src: 'img/design/jersey/jersey (22).jpg', title: 'Jersey for Football Team Vertico' },
        { src: 'img/design/jersey/jersey (23).jpg', title: 'Red Bull Racing Jersey' },
        { src: 'img/design/jersey/jersey (24).jpg', title: 'Vertico 2023 custom soccer kit' },
        { src: 'img/design/jersey/jersey (25).jpg', title: 'Two football kits for De Brabandse.' },
        { src: 'img/design/jersey/jersey (26).jpg', title: 'Vertico Soccer Jersey' },
        { src: 'img/design/jersey/jersey (27).jpg', title: 'Custom Vertico Jersey Design - VARIETY' },
        { src: 'img/design/jersey/jersey (28).jpg', title: 'Two jerseys on display - one blue and yellow striped, the other black and white striped.' },
        { src: 'img/design/jersey/jersey (29).jpg', title: 'Veritico Vested Jersey' },
        { src: 'img/design/jersey/jersey (30).jpg', title: 'Soccer Jersey Design' },
        { src: 'img/design/jersey/jersey (31).jpg', title: 'Custom Blue and White Veritico Soccer Jersey' },
        { src: 'img/design/jersey/jersey (32).jpg', title: 'Vertico Uniform Set' },
        { src: 'img/design/jersey/jersey (33).jpg', title: 'Veritico.4 Jersey Set' },
        { src: 'img/design/jersey/jersey (34).jpg', title: 'Custom Vertico Jersey' },
        { src: 'img/design/jersey/jersey (35).jpg', title: 'Custom Verstigo V2 Jersey.' },
        { src: 'img/design/jersey/jersey (36).jpg', title: 'Custom Name Red and White Veritco Jersey' },
        { src: 'img/design/jersey/jersey (37).jpg', title: 'Custom Vertico Jersey - Name and Number' },
        { src: 'img/design/jersey/jersey (38).jpg', title: 'Veritico Soccer Jersey' },
        { src: 'img/design/jersey/jersey (39).jpg', title: 'Custom Jersey Name and Number 5' },
        { src: 'img/design/jersey/jersey (40).jpg', title: 'Custom Vertico Jersey with Name and Number' },
        { src: 'img/design/jersey/jersey (41).jpg', title: 'Blue Veritico Soccer Jersey.' },
        { src: 'img/design/jersey/jersey (42).jpg', title: 'Veritico Soccer Jersey Set' },
        { src: 'img/design/jersey/jersey (43).jpg', title: 'Custom Football Jersey' },
        { src: 'img/design/jersey/jersey (44).jpg', title: 'Vertico Racing Uniform 2024' },
        { src: 'img/design/jersey/jersey (45).jpg', title: 'Vertico and VERITICO Jerseys' },
        { src: 'img/design/jersey/jersey (46).jpg', title: 'Custom VERTCOR Jerseys for Team Name 10' },
        { src: 'img/design/jersey/jersey (47).jpg', title: 'Vertico Jersey Design' },
        { src: 'img/design/jersey/jersey (48).jpg', title: 'Veritco V-neck Polo Shirt' },
        { src: 'img/design/jersey/jersey (49).jpg', title: 'Vertico Marialh #8 Jersey' },
        { src: 'img/design/jersey/jersey (50).jpg', title: 'Vertico. Space-themed purple and black shirt with logo and text' },
        { src: 'img/design/jersey/jersey (51).jpg', title: 'Custom Jersey for Gatland Crew' },
        { src: 'img/design/jersey/jersey (52).jpg', title: 'Vertico Limited Edition Jersey' },
        { src: 'img/design/jersey/jersey (53).jpg', title: 'Veritco Sponsored Kelab Usahawan Ushawar Jumper' },
        { src: 'img/design/jersey/jersey (54).jpg', title: 'Veritco Branded Polo Shirt' },
        { src: 'img/design/jersey/jersey (55).jpg', title: 'Red and white striped jersey with black and red accents.' },
        { src: 'img/design/jersey/jersey (56).jpg', title: 'Vertico 2017 Jersey' },
        { src: 'img/design/jersey/jersey (57).jpg', title: 'Custom Jersey Design for Vertico' },
        { src: 'img/design/jersey/jersey (58).jpg', title: 'Vertico.com Jersey for Fortune TT Custom Design' },
        { src: 'img/design/jersey/jersey (59).jpg', title: 'Electricity Worker Uniform' },
        { src: 'img/design/jersey/jersey (60).jpg', title: 'New Design Retro Sports Jersey' },
        { src: 'img/design/jersey/jersey (61).jpg', title: 'New Design Basketball Jersey' },
        { src: 'img/design/jersey/jersey (62).jpg', title: 'New Design Retro Jersey' },
        { src: 'img/design/jersey/jersey (63).jpg', title: 'New Design Vintage Jersey Shirt Retro Style Colors' },
        { src: 'img/design/jersey/jersey (64).jpg', title: 'New Vertigo Sports Jersey Design' },
        { src: 'img/design/jersey/jersey (65).jpg', title: 'NEW RETRO DESIGN VERTICAL JERSEY SET' },
        { src: 'img/design/jersey/jersey (66).jpg', title: 'New Design of Retro Jersey' },
        { src: 'img/design/jersey/jersey (67).jpg', title: 'New Design - Retro Collections' },
        { src: 'img/design/jersey/jersey (68).jpg', title: 'New York Knicks Retro Basketball Jersey Design' },
        { src: 'img/design/jersey/jersey (69).jpg', title: 'New Sports Mania Jersey Design' },
        { src: 'img/design/jersey/jersey (70).jpg', title: 'Wedding Wira and Arif Racing Jersey Set' },
        { src: 'img/design/jersey/jersey (71).jpg', title: 'LBK Sports Jersey - Design and Colors' },
        { src: 'img/design/jersey/jersey (72).jpg', title: 'Advertisement for ACE23 shirts' },
        { src: 'img/design/jersey/jersey (73).jpg', title: 'University of Malaya sports jersey' },
        { src: 'img/design/jersey/jersey (74).jpg', title: 'Maroon Football Kit with White Stripes and Number 1.' },
        { src: 'img/design/jersey/jersey (75).jpg', title: 'Track & Field Jersey with INTEL Text' },
        { src: 'img/design/jersey/jersey (76).jpg', title: 'Educação Blue and Black Tee Shirt' },
        { src: 'img/design/jersey/jersey (77).jpg', title: 'MotoGP Uniforms by Nitrogen Sports' },
        { src: 'img/design/jersey/jersey (78).jpg', title: 'Racing Team Jersey Design for TAG Heuer United Club' },
        { src: 'img/design/jersey/jersey (79).jpg', title: 'Colorful Robotic-Themed Jersey Design for eSports Team' },
        { src: 'img/design/jersey/jersey (80).jpg', title: 'Tone One Backfront Graphic for Two Men' },
        { src: 'img/design/jersey/jersey (81).jpg', title: 'Two MOBOT Club soccer jerseys with unique designs.' },
        { src: 'img/design/jersey/jersey (82).jpg', title: 'Sportswear Advertisement Featuring Athlete' },
        { src: 'img/design/jersey/jersey (83).jpg', title: 'Man wearing sponsored t-shirt by MBO Club' },
        { src: 'img/design/jersey/jersey (84).jpg', title: 'Malayan Royal Blue Jersey' },
        { src: 'img/design/jersey/jersey (85).jpg', title: 'Izzz Sports Printing Jersey for IsZz Brothers' },
        { src: 'img/design/jersey/jersey (86).jpg', title: 'Sports Jersey Advertisement for GMI Team' },
        { src: 'img/design/jersey/jersey (87).jpg', title: 'Black and White Soccer Jersey' },
        { src: 'img/design/jersey/jersey (88).jpg', title: 'Colorful CRM Logo on Sports Jersey' },
        { src: 'img/design/jersey/jersey (89).jpg', title: 'Sports Team Jersey Design' },
        { src: 'img/design/jersey/jersey (90).jpg', title: 'Back Design of Green Jersey with Champion and Number 24.' },
        { src: 'img/design/jersey/jersey (91).jpg', title: 'GMI Green Jersey with Champion Designation' },
        { src: 'img/design/jersey/jersey (92).jpg', title: 'Construction Company Polo Shirts' },
        { src: 'img/design/jersey/jersey (93).jpg', title: 'Team USA Rugby Blue Polo Shirt' },
        { src: 'img/design/jersey/jersey (94).jpg', title: 'Malaysian Gaming Tournament Team Shirt' },
        { src: 'img/design/jersey/jersey (95).jpg', title: 'Trucker themed polo shirts' },
    ],
    logotext: [
        { src: 'img/design/logo/cover.jpg', title: 'Blue Malaya Royal Logo' },
        { src: 'img/design/logo/7.jpg', title: 'Gema Sport Logo' },
        { src: 'img/design/logo/abudzar logo baru.png', title: 'Logo for Abudar Esports Team' },
        { src: 'img/design/logo/abudzar LOGO.png', title: 'AADR Logo 2021-2022' },
        { src: 'img/design/logo/abudzar1.png', title: 'AABD RWC 2021 Tournament Date and Logo' },
        { src: 'img/design/logo/ae231.png', title: 'Apex Legends logo for tournament' },
        { src: 'img/design/logo/ae232.png', title: 'Ace 21 Logo Design' },
        { src: 'img/design/logo/animated picture white.jpg', title: 'Animation Logo for Animated Picture' },
        { src: 'img/design/logo/apparel.png', title: 'Omar Apparel Banner Showcasing Made in Malaysia' },
        { src: 'img/design/logo/ATUSA1.PNG', title: 'USA Aviation Safety System Integration and Testing Alliance Logo' },
        { src: 'img/design/logo/ATUSA15.png', title: 'Atusa Gaming Team Logo' },
        { src: 'img/design/logo/barisan nasional.png', title: 'Banner of Indonesian National Flag' },
        { src: 'img/design/logo/biotech1.jpg', title: 'Logo of Universiti Pertahanan Nasional Malaysia (UPNM)' },
        { src: 'img/design/logo/biotech2.jpg', title: 'Science and Technology Logo' },
        { src: 'img/design/logo/biotech3.jpg', title: '2nd Biotech Conference Logo' },
        { src: 'img/design/logo/biotech5.jpg', title: '20th Anniversary Celebration for Tahun Biotech' },
        { src: 'img/design/logo/BLEAKANGCRM1.png', title: 'Mosaic of Landscapes' },
        { src: 'img/design/logo/CRM2 - FAIZ14.jpg', title: 'Colorful graphic with text and floral elements.' },
        { src: 'img/design/logo/designbelakang.png', title: 'Malaysian Institute Logo' },
        { src: 'img/design/logo/gegau.png', title: 'Gray and white pixel art.' },
        { src: 'img/design/logo/germany.png', title: 'German Football Team Emblem' },
        { src: 'img/design/logo/gm1.png', title: 'Green Movement Logo of German Malaysian Institute' },
        { src: 'img/design/logo/gm2.png', title: 'Green Moving Image Logo' },
        { src: 'img/design/logo/gm3.png', title: 'Official Green Movement Logo' },
        { src: 'img/design/logo/gm4.png', title: 'Logo of Green Movement Malaysian Institute' },
        { src: 'img/design/logo/gm5.png', title: 'Green Mover GMI Logo' },
        { src: 'img/design/logo/gm6.png', title: 'Green Mover GMI logo' },
        { src: 'img/design/logo/grafika4.png', title: 'Graphika Logo - Freedom of Expression.' },
        { src: 'img/design/logo/grafika6.png', title: 'Graphika Logo in Bold Letters' },
        { src: 'img/design/logo/grafika8.png', title: 'Graphika logo with electric lightning and comic book style typography.' },
        { src: 'img/design/logo/KPC LOGO.png', title: 'Coat of Arms for KPKC Melaka' },
        { src: 'img/design/logo/l1.jpg', title: 'Pendidipur Seni Text Logo.' },
        { src: 'img/design/logo/l2.jpg', title: 'Seni SENI Text in Colorful Background' },
        { src: 'img/design/logo/l3.jpg', title: 'Seni SENI logo on grunge background' },
        { src: 'img/design/logo/l4.jpg', title: 'Explosion of Blue Text Reading PENGLIHUR SENI' },
        { src: 'img/design/logo/L5.jpg', title: 'PENGLIPUR SENI EKSPOR' },
        { src: 'img/design/logo/L6.jpg', title: 'Metal Band Poster with Stylized Lettering' },
        { src: 'img/design/logo/l7.jpg', title: 'Adobe Photoshop logo in Indonesian.' },
        { src: 'img/design/logo/lega1.png', title: 'Legendary League of Legends Logo' },
        { src: 'img/design/logo/lega2.png', title: 'Modern Sports Team Logo Design' },
        { src: 'img/design/logo/lega3.png', title: 'Black Legacy Logo on Yellow Background' },
        { src: 'img/design/logo/lega4.png', title: 'GMI Logo on Square Background' },
        { src: 'img/design/logo/lega5.png', title: 'Two variations of a logo for GMI.' },
        { src: 'img/design/logo/lega6.png', title: 'Logo for GMI Gaming Company' },
        { src: 'img/design/logo/lega7.png', title: 'Lego Legarians Logo' },
        { src: 'img/design/logo/lega8.png', title: 'Multimedia Club Logo' },
        { src: 'img/design/logo/lega9.png', title: 'LGARIANS WORLDWIDE MEMBERSHIP LOGO' },
        { src: 'img/design/logo/limited edition.jpg', title: 'Limited Edition Collectors Box for Lone Survivor Logo' },
        { src: 'img/design/logo/logo (1).jpg', title: 'GNNW Logo for 25th Anniversary Event' },
        { src: 'img/design/logo/logo (1).png', title: 'German-Malaysian Institute' },
        { src: 'img/design/logo/logo (2).jpg', title: 'Vivo Logo Design' },
        { src: 'img/design/logo/logo (2).png', title: 'GMI Logo' },
        { src: 'img/design/logo/logo (3).jpg', title: 'University of Malaysia logo.' },
        { src: 'img/design/logo/logo (3).png', title: 'German Malaysian Malaysian Institute Logo' },
        { src: 'img/design/logo/logo (4).jpg', title: 'University Malaysia Logo' },
        { src: 'img/design/logo/logo (4).png', title: 'Last Chapter of GMI' },
        { src: 'img/design/logo/logo (5).jpg', title: 'H&H Construction Enterprise Logo' },
        { src: 'img/design/logo/logo (5).png', title: 'High Quality Jersey Tag' },
        { src: 'img/design/logo/logo (6).jpg', title: 'Construction Company Logo' },
        { src: 'img/design/logo/logo (6).png', title: 'Handball Team Logo' },
        { src: 'img/design/logo/logo (7).jpg', title: 'Construction Company Logo' },
        { src: 'img/design/logo/logo (7).png', title: 'The German Malaysian Institute Logo' },
        { src: 'img/design/logo/logo (8).jpg', title: 'H&H Construction Enterprise Logo' },
        { src: 'img/design/logo/logo (8).png', title: 'German Malaysian Art Logo' },
        { src: 'img/design/logo/logo (9).jpg', title: 'Construction company logo.' },
        { src: 'img/design/logo/logo (9).png', title: 'Malaya Streetwear Logo' },
        { src: 'img/design/logo/logo (10).jpg', title: '1 DAYS LEFT TO BUY YOUR GMI OLD SHOE JERSEY' },
        { src: 'img/design/logo/logo (10).png', title: 'Logo for University of Malaya' },
        { src: 'img/design/logo/logo (11).jpg', title: 'Silver and black VVV logo on black background.' },
        { src: 'img/design/logo/logo (11).png', title: 'Emblem of an organization with crescent and star motif.' },
        { src: 'img/design/logo/logo (12).jpg', title: 'Brand Logo of Yves Saint Laurent' },
        { src: 'img/design/logo/logo (12).png', title: 'No Smoking Sign in Red and White' },
        { src: 'img/design/logo/logo (13).jpg', title: 'VVV Logo' },
        { src: 'img/design/logo/logo (13).png', title: 'Logo for Malaysian Institute of Science and Technology' },
        { src: 'img/design/logo/logo (14).jpg', title: 'Logo of VVVV for mens clothing line' },
        { src: 'img/design/logo/logo (14).png', title: 'Gothic Font with Name Imprinted' },
        { src: 'img/design/logo/logo (15).jpg', title: 'VVV Logo' },
        { src: 'img/design/logo/logo (16).jpg', title: 'Vulcain esports logo' },
        { src: 'img/design/logo/logo (17).jpg', title: 'Sigma Logo on Black Background' },
        { src: 'img/design/logo/logo (18).jpg', title: 'Raja Muda Selangor Sports Event Poster' },
        { src: 'img/design/logo/logo (19).jpg', title: 'University of Malaya Logo' },
        { src: 'img/design/logo/logo (20).jpg', title: 'Logo for WARM WOLF' },
        { src: 'img/design/logo/logo (21).jpg', title: 'UM Logo on Black Background' },
        { src: 'img/design/logo/logo (22).jpg', title: 'University Malaya Logo' },
        { src: 'img/design/logo/logo (23).jpg', title: 'University Malacca Logo' },
        { src: 'img/design/logo/logo (24).jpg', title: 'Rock Band Logo Design with Text and Graphics' },
        { src: 'img/design/logo/logo (25).jpg', title: 'Hahaha Sambodhaja 2019 Established' },
        { src: 'img/design/logo/logo bawah.png', title: 'Awareness Anti-Bullying Campaign Poster' },
        { src: 'img/design/logo/logo crm3.png', title: 'Crimson Logo on Black Background' },
        { src: 'img/design/logo/logo gmi6.png', title: 'Green Welfare Club Logo' },
        { src: 'img/design/logo/logo poknik.jpg', title: 'ADA 2021 Logo' },
        { src: 'img/design/logo/logo1(1).jpg', title: 'Hamburger graphic with Sams Signature Burger logo and text' },
        { src: 'img/design/logo/logo2(1).jpg', title: 'Sams Signature Burger Logo' },
        { src: 'img/design/logo/logo3(1).jpg', title: 'Sams signature burger logo' },
        { src: 'img/design/logo/logo4(1).jpg', title: 'Burger Sams Signature Logo' },
        { src: 'img/design/logo/logo5(1).jpg', title: 'Sams Signature Fresh and Tasty Logo' },
        { src: 'img/design/logo/logo6(1).jpg', title: 'Sams Signature Burger Logo' },
        { src: 'img/design/logo/logoo.png', title: 'GERMAN-MALAYSIAN INSTITUTE LOGO' },
        { src: 'img/design/logo/logoo3.jpg', title: 'German Malaysian Institute' },
        { src: 'img/design/logo/LTD.png', title: 'Limited Edition Logo Design' },
        { src: 'img/design/logo/moksha.png', title: 'Red Logo on Grey Background' },
        { src: 'img/design/logo/Myself Cover(1).png', title: 'Cartoon Illustration of a Yellow Chocolate Milk Containers With Ahmads Name and Crm 2Ctmt Written...' },
        { src: 'img/design/logo/Myself Cover.png', title: 'Cartoon Stylized Milkshake Illustration' },
        { src: 'img/design/logo/NOW OR NEVER.png', title: 'Blurred Text Image' },
        { src: 'img/design/logo/ONN DUTY ILLUSTRATION.png', title: 'On Duty Truck Driver HH Logo' },
        { src: 'img/design/logo/POSTER122.jpg', title: 'Colorful Poster for Penglipur Seni Event' },
        { src: 'img/design/logo/projek sawi.png', title: 'Project JAVANISSIWA logo on black background.' },
        { src: 'img/design/logo/sma7.png', title: 'Embassy of Bosnia and Herzegovina Emblem' },
        { src: 'img/design/logo/SPORTSCEINCE SEJAYA.jpg', title: 'Sport Science SEGA Style' },
        { src: 'img/design/logo/STICKER MOTO.png', title: 'GMI Student Hostel Signage' },
        { src: 'img/design/logo/the grato.png', title: 'Blurred image of text logo.' },
        { src: 'img/design/logo/unimalaya logo.png', title: 'Malacca University Logo' },
        { src: 'img/design/logo/vc1.png', title: 'Image of football stadium at night with message about support for UBU.' },
        { src: 'img/design/logo/white logo.png', title: 'Text-based Image' },
    ],
    customart: [
        { src: 'img/design/custom/cover.jpg', title: 'Comic Book Cover Featuring Superheroes Promoting Sustainable Lifestyle' },
        { src: 'img/design/custom/adult.png', title: 'Illustration of an adult male character.' },
        { src: 'img/design/custom/aqil.png', title: 'Man in Suit at Podium' },
        { src: 'img/design/custom/camera angle1 (draw).png', title: 'Gameplay Animation Still Images' },
        { src: 'img/design/custom/camera angle2 (draw).png', title: 'Strip Game Show Video Montage for Entertainment' },
        { src: 'img/design/custom/character1.png', title: 'Character Design for Mr. John Wick' },
        { src: 'img/design/custom/character2.png', title: 'Character Design with Profession Detail' },
        { src: 'img/design/custom/character3.png', title: 'Side Character Illustration - Mr. Aurelio, Insurance Broker' },
        { src: 'img/design/custom/comic1.png', title: 'Animated Comic Strip with Various Scenes' },
        { src: 'img/design/custom/comic2.png', title: 'Animated Storyboard for Video Ad Campaign' },
        { src: 'img/design/custom/custom (1).jpg', title: 'Intergenerational Caregiving Poster' },
        { src: 'img/design/custom/custom (1).png', title: 'GMI Song Composition Contest Poster' },
        { src: 'img/design/custom/custom (2).jpg', title: 'Anti-War Propaganda Poster' },
        { src: 'img/design/custom/custom (2).png', title: 'Pixelated Train Design' },
        { src: 'img/design/custom/custom (3).jpg', title: 'Jangan Sampai Kehilangan Hak (Indonesian Anti-Graft Poster)' },
        { src: 'img/design/custom/custom (3).png', title: 'Man with digital face painting at night' },
        { src: 'img/design/custom/custom (4).jpg', title: 'Coloring Book Page Featuring Man in Shower' },
        { src: 'img/design/custom/custom (4).png', title: 'Face Painted in Splatter Pattern' },
        { src: 'img/design/custom/custom (5).jpg', title: 'Two Women Sharing a Meal' },
        { src: 'img/design/custom/custom (6).jpg', title: 'I-Code Model Infographic' },
        { src: 'img/design/custom/custom (7).jpg', title: 'Black calligraphy script on white background' },
        { src: 'img/design/custom/custom (8).jpg', title: 'Colorful Building Rooftops' },
        { src: 'img/design/custom/custom (9).jpg', title: 'Man with digitally altered face taking selfie.' },
        { src: 'img/design/custom/d (1).jpeg', title: 'Row of Classroom Chairs' },
        { src: 'img/design/custom/d (1).png', title: 'Geometric Drawing of Triangle Area Measurement' },
        { src: 'img/design/custom/d (2).png', title: 'Compound Angle Geometry Problem' },
        { src: 'img/design/custom/d (3).png', title: 'Sine Rule Geometry Problem Illustration' },
        { src: 'img/design/custom/d (4).png', title: 'Special Angles Illustration' },
        { src: 'img/design/custom/d (5).png', title: 'Geometric Problem: Finding Angle B Given Equilateral Triangle and Circumradius' },
        { src: 'img/design/custom/d (6).png', title: 'Ancient Geometric Drawing' },
        { src: 'img/design/custom/d (7).png', title: 'Angle of Circle and Diamond' },
        { src: 'img/design/custom/d (8).png', title: 'Geometric Pattern' },
        { src: 'img/design/custom/d (9).png', title: 'Circular Drawing Problem' },
        { src: 'img/design/custom/d (10).png', title: 'Circular Drawing with Diameter and Radius' },
        { src: 'img/design/custom/d (11).png', title: 'Circle Geometry Exercise Worksheet' },
        { src: 'img/design/custom/d (12).png', title: 'Brown wooden box with lid.' },
        { src: 'img/design/custom/d (13).png', title: 'Geometric Construction Drawing' },
        { src: 'img/design/custom/d (14).png', title: 'Calculation of sector height and angle in geometric drawing.' },
        { src: 'img/design/custom/d (15).png', title: 'Circular Geometric Drawing' },
        { src: 'img/design/custom/d (16).png', title: 'Geometric Riddle Involving Circle and Square' },
        { src: 'img/design/custom/d (17).png', title: 'Geometric Shapes in a Diagram' },
        { src: 'img/design/custom/d (18).png', title: 'Calculating the Triangle Area' },
        { src: 'img/design/custom/d (19).png', title: 'Circular Diagram of Geometric Dimensions' },
        { src: 'img/design/custom/d (20).png', title: 'ABU B. MUSTAFA PROFILE DRAWING' },
        { src: 'img/design/custom/d (21).png', title: 'Floor Plan of Residential Building' },
        { src: 'img/design/custom/d (22).png', title: 'Geometry Diagram: Rectangles and Angles' },
        { src: 'img/design/custom/d (23).png', title: 'Illustrative Example of Cosine Rule' },
        { src: 'img/design/custom/d (24).png', title: 'Emotion Chart for Basic Emotions' },
        { src: 'img/design/custom/d (25).png', title: 'Emotions and Mood Expression in Cartoon Characters' },
        { src: 'img/design/custom/d (26).png', title: 'Illustration of Malay female with information on age, height, ethnicity.' },
        { src: 'img/design/custom/d (27).png', title: 'Portrait of Bainun Binthi Harun' },
        { src: 'img/design/custom/d (28).png', title: 'Calculate Outside Area of Museum' },
        { src: 'img/design/custom/d (29).png', title: 'Diagram of Euclidean Geometry' },
        { src: 'img/design/custom/d (30).png', title: 'Drawing of an electrical circuit diagram.' },
        { src: 'img/design/custom/d (31).png', title: 'Calculation of Angle Using Protractor' },
        { src: 'img/design/custom/d (32).png', title: 'Mathematical Geometric Diagrams Showing Angle and Triangle Constructions' },
        { src: 'img/design/custom/d (33).png', title: 'Geometric Proof of Angle Sum Property' },
        { src: 'img/design/custom/d (34).png', title: 'Geometric Calculations on Angle and Triangle' },
        { src: 'img/design/custom/d (35).png', title: 'Geometric Angle Measurement Calculation Diagram' },
        { src: 'img/design/custom/d (36).png', title: '3D Model of a Cube in Red and Gray' },
        { src: 'img/design/custom/d (37).png', title: 'Calculation of angle between laser beam and ruler.' },
        { src: 'img/design/custom/d (38).png', title: 'Angle Calculation in 3D Graphics' },
        { src: 'img/design/custom/d (39).png', title: 'Calculate angle under laser' },
        { src: 'img/design/custom/d (40).png', title: 'Laser Triangle Calculation Problem' },
        { src: 'img/design/custom/d (41).png', title: 'Calculation of laser beam angle' },
        { src: 'img/design/custom/d (42).png', title: 'Red Angle Triangle Calculation' },
        { src: 'img/design/custom/d (43).png', title: 'Measurements for Display Area at Museum' },
        { src: 'img/design/custom/d (44).png', title: 'Geometric Drawing Diagram' },
        { src: 'img/design/custom/d (45).png', title: 'Side View of Building Plan' },
        { src: 'img/design/custom/d (46).png', title: 'Calculate volume of museum exhibit' },
        { src: 'img/design/custom/d (47).png', title: 'Doorway Dimension for Tall Man' },
        { src: 'img/design/custom/d (48).png', title: 'The Pen Moo Moo Cottage' },
        { src: 'img/design/custom/d (49).png', title: 'Geometric Box Diagram' },
        { src: 'img/design/custom/d (50).png', title: 'Equation of Quadrant' },
        { src: 'img/design/custom/e1.png', title: 'Expressions of an Emo Boy' },
        { src: 'img/design/custom/e2.png', title: 'The Evolution of Emotions' },
        { src: 'img/design/custom/e3.png', title: 'Cartoon Man Emoji Face Reactions' },
        { src: 'img/design/custom/faris2.PNG', title: 'Shirtless man riding bicycle.' },
        { src: 'img/design/custom/father emotions.png', title: 'Variety of emotions on cartoon mans faces.' },
        { src: 'img/design/custom/father old emotion.png', title: 'Variety of Expression in Emoticon Styles' },
        { src: 'img/design/custom/father old.png', title: 'Illustration of a male character from the comic series' },
        { src: 'img/design/custom/father.png', title: 'Sketch of Male Character in Casual Shirt' },
        { src: 'img/design/custom/gmi crm.png', title: 'Skeleton Powering Up' },
        { src: 'img/design/custom/kid.png', title: 'Character design for Abu B Mustafa - age 7, ethnicity from Malaysia.' },
        { src: 'img/design/custom/man.png', title: 'Illustration of male character with name and attributes.' },
        { src: 'img/design/custom/medicresearch (1).png', title: 'Surgical Bone Repair Implant' },
        { src: 'img/design/custom/medicresearch (2).png', title: 'Clinical Medical Illustration' },
        { src: 'img/design/custom/medicresearch (3).png', title: 'Surgical procedure in progress' },
        { src: 'img/design/custom/medicresearch (4).png', title: 'Innovative Knee Brace Technology' },
        { src: 'img/design/custom/medicresearch (5).png', title: 'Anatomical 3D rendering of hip joint replacement procedure.' },
        { src: 'img/design/custom/medicresearch (6).png', title: 'Medical Implant Procedure on Knee' },
        { src: 'img/design/custom/mother old emotions.png', title: 'Facial Emotions Illustration - Womans Faces in Different Expressions' },
        { src: 'img/design/custom/mother old.png', title: 'Cartoon Character Profile: Bainun Binni Hariun' },
        { src: 'img/design/custom/mother.png', title: 'Girls color scheme illustration' },
        { src: 'img/design/custom/pulut1.jpg', title: 'Yeezy Shoe Flying Over Rural Italy' },
        { src: 'img/design/custom/robot view 2.png', title: 'Robot Character Variations' },
        { src: 'img/design/custom/robot view 3.png', title: 'Robotic Vehicles and Inventions in Black and White' },
        { src: 'img/design/custom/robot view front.png', title: 'A Cartoon Robot' },
        { src: 'img/design/custom/robot view side.png', title: 'Pair of black and white cat paws' },
        { src: 'img/design/custom/robot view up.png', title: 'Robotic Arm Machine Illustration' },
        { src: 'img/design/custom/storyboard.png', title: 'Thumbnail Storyboard for Star Wars Episode' },
        { src: 'img/design/custom/teen.png', title: 'Character Design: A Male Teenager with Short Hair and a Light Skin Tone' },
        { src: 'img/design/custom/avatar/1.quai young.png', title: 'Quarai Teenage Character Design' },
        { src: 'img/design/custom/avatar/2.Quai middle.png', title: 'Quad Middle Character Designs' },
        { src: 'img/design/custom/avatar/3.Quai old.png', title: 'Character Designs for Quadra

Quadra refers to a character in a style that appears to be inspired...' },
        { src: 'img/design/custom/avatar/4.Azazil.png', title: 'Azil Character Sketch' },
        { src: 'img/design/custom/avatar/5.Aroush.png', title: 'Arukh Crest: Stylized Elven Armor Design' },
        { src: 'img/design/custom/avatar/6.Leluhur.png', title: 'Lejahur - Mythical Turtle Character' },
        { src: 'img/design/custom/avatar/air.png', title: 'Cartoon Character in Martial Arts Stance' },
        { src: 'img/design/custom/avatar/blaze.png', title: 'Blade - Character in Action' },
        { src: 'img/design/custom/avatar/earth.png', title: 'Cartoon illustration of an adventurer encountering a collapsed Earth.' },
        { src: 'img/design/custom/avatar/fire.png', title: 'Animation of Warrior Casting Flame Spell' },
        { src: 'img/design/custom/storyboard/storyboard1.png', title: 'A Series of Unfortunate Events: Comic Book Pages' },
        { src: 'img/design/custom/storyboard/storyboard2.png', title: 'A Day in the Life of an Online Gamer' },
        { src: 'img/design/custom/storyboard/storyboard3.png', title: 'Comic Strip' },
        { src: 'img/design/custom/storyboard/storyboard4.png', title: 'Multipanel Comic Strip Featuring Three Men' },
        { src: 'img/design/custom/storyboard/storyboard5.png', title: 'Comics Strip with Dialogue Bubbles' },
        { src: 'img/design/custom/storyboard/storyboard6.png', title: 'Cartoon Comic Series: A Mans Reactions to Various Situations' },
    ],
    sticker: [
        { src: 'img/design/stickers/cover.jpg', title: 'A Simpson Cartoon Parodying German Money' },
        { src: 'img/design/stickers/sticker jet1.png', title: 'GOLDEN GLORY TOURNAMENT POSTER FOR GATHERING' },
        { src: 'img/design/stickers/STICKER KRETA gold.png', title: 'Arabic script on black background' },
        { src: 'img/design/stickers/stickers (1).jpg', title: 'Free gift stickers for GMI Suka Gadhu' },
        { src: 'img/design/stickers/stickers (1).png', title: 'Collection of GMI Stamps' },
        { src: 'img/design/stickers/stickers (2).png', title: 'Poster for Pelajaran 2020 at Universiti Sains Islam Malaysia' },
        { src: 'img/design/stickers/stickers (3).png', title: 'Logo of an organization promoting sports and wellness for women' },
        { src: 'img/design/stickers/stickers (4).png', title: 'ANIYAK NABI NAKAL WARRIORS SPORTS LOGO' },
        { src: 'img/design/stickers/stickers (6).png', title: 'ID Card for Pelajaran UMP 2021/2022' },
        { src: 'img/design/stickers/stickers (7).png', title: 'Universiti Malaya Event Ticket 2022/2023' },
        { src: 'img/design/stickers/stickers (8).png', title: 'Certificate of SESI 2022/2023' },
        { src: 'img/design/stickers/stickers (9).png', title: 'Student Hostel Zone (GMI) 2023-2024' },
        { src: 'img/design/stickers/stickers (10).jpg', title: 'Markah Kiss Four Pack Stickers' },
        { src: 'img/design/stickers/stickers (11).jpg', title: 'Freegift stickers. No parking allowed anywhere' },
        { src: 'img/design/stickers/stickers (12).jpg', title: 'Winnie the Pooh Free Stickers Offer' },
        { src: 'img/design/stickers/stickers (13).jpg', title: 'Fast & Furious Stickers' },
        { src: 'img/design/stickers/stickers (14).jpg', title: 'The Simpsons Freegift Stickers' },
        { src: 'img/design/stickers/stickers (15).jpg', title: 'Free Sticker Pack Advertisement' },
        { src: 'img/design/stickers/stickers (16).jpg', title: 'Freegift Stickers - Engineering Puns' },
        { src: 'img/design/stickers/stickers (17).jpg', title: 'Freegift Stickers for Anakkaras Stahi.' },
        { src: 'img/design/stickers/stickers (18).jpg', title: 'Plastic Hetam Logo' },
    ],
    products: [
        { src: 'img/design/product/cover.png', title: 'Todays Special Health Oil Promotion Poster' },
        { src: 'img/design/product/5800894.png', title: 'Project SAW logo on brick wall' },
        { src: 'img/design/product/6239674.png', title: 'Outdoor Advertising Billboard in Urban Setting' },
        { src: 'img/design/product/business card back.png', title: 'QR code for Ahmad Fazilah - Founder of Projectsawi.com' },
        { src: 'img/design/product/business card front.png', title: 'Projet SAWI Spice Mix Advertisement' },
        { src: 'img/design/product/card1.png', title: 'CEO Profile for Mohammad Nizamuddin at Jet Designs' },
        { src: 'img/design/product/card2.png', title: 'N2T Industrial Design Logo for Aerospace Company' },
        { src: 'img/design/product/card3.png', title: 'Aesthetic Calligraphy Design for Tea Set' },
        { src: 'img/design/product/card4.png', title: 'Airline Company Logo Design' },
        { src: 'img/design/product/card5.png', title: 'Jet Design Logo for Aviation Company' },
        { src: 'img/design/product/card6.png', title: 'Business Card for Bin Mohd Nasser' },
        { src: 'img/design/product/COVER1.png', title: 'Modern Calligraphy Artwork' },
        { src: 'img/design/product/cover2.jpg', title: 'Bukit Timah Mosque Sign' },
        { src: 'img/design/product/COVER2.png', title: 'Celtic Cross Logo with Lettering' },
        { src: 'img/design/product/cover3.jpg', title: 'Cover of an Arabic Book' },
        { src: 'img/design/product/COVER3.png', title: 'Eid Mubarak Poster with Arabic Text' },
        { src: 'img/design/product/cover4.jpg', title: 'Green Banner with White Arabic Text' },
        { src: 'img/design/product/COVER4.png', title: 'Abstract Artwork in Grayscale' },
        { src: 'img/design/product/cover5.jpg', title: 'Islamic Education Textbook Cover for 2016' },
        { src: 'img/design/product/COVER5.png', title: 'Mosaic collage of community activities and achievements.' },
        { src: 'img/design/product/COVER6.png', title: 'Colorful Abstract Art Poster' },
        { src: 'img/design/product/COVER7.png', title: 'Poster for Edisi Ke-54 of Kedah Football Team Fan Meet' },
        { src: 'img/design/product/COVER8.png', title: 'Islamic Calligraphy Poster with Arabic Text' },
        { src: 'img/design/product/COVER9.png', title: 'Book Cover of Poetry Collection in Persian Script' },
        { src: 'img/design/product/coverfilter.png', title: 'Poster for 2019 Election Campaign' },
        { src: 'img/design/product/food sticker.png', title: 'Fish Head Curry Food Poster' },
        { src: 'img/design/product/kisas.jpg', title: 'Multi-colored buildings in urban setting' },
        { src: 'img/design/product/KULIT2.png', title: 'Green fabric with Arabic calligraphy.' },
        { src: 'img/design/product/Logo_Mockup_070.png', title: 'Project Savi Business Card' },
        { src: 'img/design/product/packaging2.png', title: 'Mustard Flavored Snack Crackers' },
        { src: 'img/design/product/packaging3.png', title: 'Organic Mustard Jar Label' },
        { src: 'img/design/product/packaging4.png', title: 'Nutrition Fact Label for Mustard Seeds Oil' },
        { src: 'img/design/product/Pickel.png', title: 'Container of mustard pickles.' },
        { src: 'img/design/product/poster4x.PNG', title: 'Colorful image promoting mustard and seeds as ingredients for a healthier diet.' },
        { src: 'img/design/product/powder.png', title: 'Mustard Powder Packaging' },
        { src: 'img/design/product/projek sawi.png', title: 'Modern Home Office Design with Clean Lines' },
        { src: 'img/design/product/sauce.png', title: 'Project Saw - Mustard Oil' },
        { src: 'img/design/product/seeds.png', title: 'Organic Premium Seeds in Bottle' },
        { src: 'img/design/product/signboard1.png', title: 'City billboard advertisement for Mustard and Muffins' },
        { src: 'img/design/product/sticker1.png', title: 'MUSTARD POWDER FROM PROJEK SWI WITH VITAMIN C D3 RON' },
        { src: 'img/design/product/top.png', title: 'Projekt Sawi Logo' },
        { src: 'img/design/product/yellow mustard.png', title: 'Yellow glue bottle with dropper' },
    ],
    mcletter: [
        { src: 'img/design/mc/cover.jpg', title: 'Medical Certificate from SJS Polislinkan An Nur' },
        { src: 'img/design/mc/mc (1).jpg', title: 'UMP University Identity Card' },
        { src: 'img/design/mc/mc (2).jpg', title: 'Arabic Government Document with Red Seal and Signature' },
        { src: 'img/design/mc/mc (3).jpg', title: 'Polling Booth Registration Form for Voting' },
        { src: 'img/design/mc/mc (4).jpg', title: 'A letter from the Ministry of Health Malaysia regarding guidelines for hospitals.' },
    ],
    others: [
        { src: 'img/design/others/cover.jpg', title: 'Black and red flame design baseball cap' },
        { src: 'img/design/others/barangpost2.jpg', title: 'Colorful Varsity Jackets Featuring Designs of Dragons and Flowers.' },
        { src: 'img/design/others/others (1).jpg', title: 'University Malaysia Kelantan Official Merchandise' },
        { src: 'img/design/others/others (2).jpg', title: 'Universiti Malaysia Melaka Gildan Cap' },
        { src: 'img/design/others/others (3).jpg', title: 'University Merchandise Cap with Embroidery' },
        { src: 'img/design/others/others (4).jpg', title: 'University of Malaya Gildan Cap Collection' },
        { src: 'img/design/others/others (5).jpg', title: 'Universiti Malaya Gildan Cap' },
        { src: 'img/design/others/others (6).jpg', title: 'University of Malaya Gildan Cap' },
        { src: 'img/design/others/others (7).jpg', title: 'The image depicts a stylized graphic with elements related to sports, specifically soccer. At the...' },
        { src: 'img/design/others/others (8).jpg', title: 'Two men in matching jackets standing side by side.' },
        { src: 'img/design/others/others (9).jpg', title: 'Menjerit Championship Poster Featuring Three Athletes' },
        { src: 'img/design/others/poster.jpg', title: 'Athletic Wear for Team

The image shows a set of athletic wear that appears to be designed for a ...' },
        { src: 'img/design/others/poster1.jpg', title: 'Jacket with unique graphic design and text' },
    ],
    banner: [
        { src: 'img/design/banner/cover.jpg', title: 'ExcellentProfits Logo Display and Promotional Sign' },
        { src: 'img/design/banner/banner (1).jpg', title: 'Sams Sandwich Advertisement' },
        { src: 'img/design/banner/banner (1).png', title: 'Vibrant Future Themed Childrens Event Poster with Candy and Balloons' },
        { src: 'img/design/banner/banner (2).jpg', title: 'Sams sandwich advertisement poster' },
        { src: 'img/design/banner/banner (3).jpg', title: 'Sams Sandwich Advertisement' },
        { src: 'img/design/banner/banner (4).jpg', title: 'Sams Burger Co. Menu Featuring Beef, Chicken, and Lamb Burgers' },
        { src: 'img/design/banner/banner (5).jpg', title: 'Art Showcase Poster for GAMM Event' },
        { src: 'img/design/banner/banner (6).jpg', title: 'GAMING TOURNAMENT POSTER FOR SENGOKU EVENT' },
        { src: 'img/design/banner/banner (7).jpg', title: 'Banner for Excellent Profits with Company Name and Logo' },
        { src: 'img/design/banner/banner (8).jpg', title: 'A Sign Pointing to the Left' },
        { src: 'img/design/banner/banner (9).jpg', title: 'Excellent Proposals Signage at Hive, MMRDA Park' },
        { src: 'img/design/banner/banner (10).jpg', title: 'Event Invitation for Excellent Proposals at Hive, MMRDA Park' },
    ],
    nft: [
        { src: 'img/design/nft/cover.png', title: 'Monkey in Naval Uniform' },
        { src: 'img/design/nft/nft (1).png', title: 'Smiling Cartoon Man in White T-shirt' },
        { src: 'img/design/nft/nft (2).png', title: 'Smiling cartoon man in blue shirt' },
        { src: 'img/design/nft/nft (3).png', title: 'A cartoon of a male character smiling at the camera.' },
        { src: 'img/design/nft/nft (4).png', title: 'Man in Suit' },
        { src: 'img/design/nft/nft (5).png', title: 'Cartoon Male Character in White Polo Shirt' },
        { src: 'img/design/nft/nft (6).png', title: 'Man in black shirt.' },
        { src: 'img/design/nft/nft (7).png', title: 'Man in purple shirt' },
        { src: 'img/design/nft/nft (8).png', title: 'Cowboy Cartoon Character' },
        { src: 'img/design/nft/nft (9).png', title: 'A Demonic Fireball Skull' },
        { src: 'img/design/nft/nft (10).png', title: 'Ninja Cartoon Character' },
        { src: 'img/design/nft/nft (11).png', title: 'Ninja Cartoon Character' },
        { src: 'img/design/nft/nft (12).png', title: 'SpongeBob SquarePants Meme' },
        { src: 'img/design/nft/nft (13).png', title: 'Skeleton in Suit' },
        { src: 'img/design/nft/nft (14).png', title: 'A cartoon guy wearing a blue shirt and a slight smirk.' },
        { src: 'img/design/nft/nft (15).png', title: 'Police Officer Cartoon Illustration' },
        { src: 'img/design/nft/nft (16).png', title: 'Police officer in uniform' },
        { src: 'img/design/nft/nft (17).png', title: 'The Illustration of a Robot Character' },
        { src: 'img/design/nft/nft (18).png', title: 'Scary Clown Mask Costume Illustration' },
        { src: 'img/design/nft/nft (19).png', title: 'Red Devil Cartoon' },
        { src: 'img/design/nft/nft (20).png', title: 'Cartoon Dude Stylized Character' },
        { src: 'img/design/nft/nft (21).png', title: 'Cartoon Illustration of Male Character Wearing Chain Necklace' },
        { src: 'img/design/nft/nft (22).png', title: 'Hipster Cartoon Character Smiling' },
        { src: 'img/design/nft/nft (23).png', title: 'A Creepy Meme of Splattered Custard on a Boys Face' },
        { src: 'img/design/nft/nft (24).png', title: 'Zombie Hunter in Trench Coat and Gas Mask' },
        { src: 'img/design/nft/nft (25).png', title: 'Blue Ninja Robot' },
        { src: 'img/design/nft/nft (26).png', title: 'A Cartoon Stormtrooper' },
        { src: 'img/design/nft/nft (27).png', title: 'Darth Vaders iconic pose.' },
        { src: 'img/design/nft/nft (28).png', title: 'Stormtrooper in white armor' },
        { src: 'img/design/nft/nft (29).png', title: 'Skull Astronaut Cartoon' },
        { src: 'img/design/nft/nft (30).png', title: 'Man in Red Suit and Shades' },
        { src: 'img/design/nft/nft (31).png', title: 'Man With Skeletal Facial Features in Blue Shirt' },
        { src: 'img/design/nft/nft (32).png', title: 'Purple Thor with Angry Expression' },
        { src: 'img/design/nft/nft (33).png', title: 'Man in Suit Listening to Headphones' },
    ],
    photography: [
        { src: 'img/design/photography/cover.jpg', title: 'Family Portrait in Traditional Ethnic Garb' },
        { src: 'img/design/photography/1.jpg', title: 'Man in traditional Malay outfit' },
        { src: 'img/design/photography/2.png', title: 'Man in Blue and Black Traditional Attire' },
        { src: 'img/design/photography/3.jpg', title: 'Man wearing Jeep sweatshirt.' },
        { src: 'img/design/photography/4.JPG', title: 'Man in Jeep Sweatshirt and Khaki Pants' },
        { src: 'img/design/photography/5.jpg', title: 'Man holding certificate' },
        { src: 'img/design/photography/6.PNG', title: 'Man in water holding flags from Malaysia and Indonesia.' },
        { src: 'img/design/photography/7.png', title: 'Bloodied and Crying Masked Figure' },
        { src: 'img/design/photography/8.png', title: 'Man in hoodie on phone' },
        { src: 'img/design/photography/9.png', title: 'Two Men in Formal Shirts' },
        { src: 'img/design/photography/10.png', title: 'Malnourished man riding bicycle.' },
        { src: 'img/design/photography/m1.jpg', title: 'Photography by Maha Ahmad Fairoz' },
        { src: 'img/design/photography/m2.jpg', title: 'QR Code on Waves' },
        { src: 'img/design/photography/m3.jpg', title: 'VOLTAREN FACE OFF - PRODUCT PHOTOGRAPHY' },
        { src: 'img/design/photography/m4.jpg', title: 'Fashion Trendsetter: Street Style Photography Featuring Three Different Looks.' },
        { src: 'img/design/photography/m5.jpg', title: 'Comic Con Character Gallery' },
        { src: 'img/design/photography/m5.PNG', title: 'Spices and Seasoning' },
        { src: 'img/design/photography/m6.jpg', title: 'Minimalist Building Front with Yellow Letter A' },
        { src: 'img/design/photography/m7.jpg', title: 'Graffiti Art and Words Mosaic' },
        { src: 'img/design/photography/m8.jpg', title: 'Toys Display' },
        { src: 'img/design/photography/m9.jpg', title: 'Light Trail of Vehicles on Highway' },
        { src: 'img/design/photography/m10.jpg', title: 'Reflection Artwork' },
        { src: 'img/design/photography/m11.jpg', title: 'Silhouette Album Cover' },
        { src: 'img/design/photography/m12.jpg', title: 'Two Side by Side Selfie of Smiling Men' },
        { src: 'img/design/photography/m13.jpg', title: 'Modern Architectural Designs on Buildings' },
        { src: 'img/design/photography/m14.jpg', title: 'Street Scenes' },
        { src: 'img/design/photography/m15.jpg', title: 'Chicken Sandwich with Fries' },
        { src: 'img/design/photography/m16.jpg', title: 'Nature Photography Poster Showcasing Landscapes and Wildlife.' },
        { src: 'img/design/photography/m17.jpg', title: 'SOCIAL DISTANCING' },
        { src: 'img/design/photography/m18.jpg', title: 'Hands Holding Hair Spray' },
        { src: 'img/design/photography/m19.jpg', title: 'Cosmetics Display Case' },
        { src: 'img/design/photography/m20.jpg', title: 'Colorful Stationery Set' },
        { src: 'img/design/photography/m21.jpg', title: 'Bookstore Visit - Student Life' },
        { src: 'img/design/photography/m22.jpg', title: 'Spices for Cooking and Health Benefits' },
        { src: 'img/design/photography/m23.PNG', title: 'Sticks of cinnamon' },
        { src: 'img/design/photography/m24.PNG', title: 'Bottles of spices on table' },
        { src: 'img/design/photography/m25.PNG', title: 'Two glass bottles containing herbs and spices.' },
        { src: 'img/design/photography/m26.PNG', title: 'Indian Spice Ingredients' },
        { src: 'img/design/photography/m27.PNG', title: 'Spices on white background' },
        { src: 'img/design/photography/p1.jpg', title: 'Two males practicing martial arts in front of nature setting.' },
        { src: 'img/design/photography/p2.jpg', title: 'Two men greeting each other.' },
        { src: 'img/design/photography/p3.jpg', title: 'Two men practicing martial arts' },
        { src: 'img/design/photography/p4.jpg', title: 'Two Men Boxing Outside' },
        { src: 'img/design/photography/p5.jpg', title: 'Two men conversing by a hut in an outdoor setting.' },
        { src: 'img/design/photography/p6.jpg', title: 'Man smiling at camera while showing catch of day' },
        { src: 'img/design/photography/p7.jpg', title: 'Two men holding large fish outside.' },
        { src: 'img/design/photography/p8.jpg', title: 'Men at truck stop, laughing and sharing stories.' },
        { src: 'img/design/photography/p9.jpg', title: 'Two men in car' },
        { src: 'img/design/photography/p10.jpg', title: 'Two men in car, one driving.' },
        { src: 'img/design/photography/p11.jpg', title: 'Two men praying together on stairs' },
    ],
    socialmedia: [
        { src: 'img/design/socialmedia/cover.jpg', title: 'Vertico Orange Cartoon Character Poster for Monday to Friday Operation Hour.' },
        { src: 'img/design/socialmedia/fb1.jpg', title: 'Customer feedback message exchange' },
        { src: 'img/design/socialmedia/fb2.jpg', title: 'Customer Feedback Response - Brand Expression' },
        { src: 'img/design/socialmedia/fb3.jpg', title: 'Customer Feedback Text Message Conversation' },
        { src: 'img/design/socialmedia/fb4.jpg', title: 'Customer Feedback Chat' },
        { src: 'img/design/socialmedia/fb5.jpg', title: 'Customer Feedback Message Display' },
        { src: 'img/design/socialmedia/fb6.jpg', title: 'Customer Feedback Conversation' },
        { src: 'img/design/socialmedia/fb7.jpg', title: 'Customer feedback thank you message with photo of mosque.' },
        { src: 'img/design/socialmedia/fb8.jpg', title: 'Customer Feedback Text Message Conversation' },
        { src: 'img/design/socialmedia/fb9.jpg', title: 'Customer Feedback Messenger Conversation' },
        { src: 'img/design/socialmedia/fb10.jpg', title: 'Customer Feedback Poster' },
        { src: 'img/design/socialmedia/INTERNSHIP 25.jpg', title: '5 Set Realistic Expectations Advice Image' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS1.jpg', title: 'Internship Tips Graphic' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS2.jpg', title: 'Research Graphic Organizer for Job Interview Preparation' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS3.jpg', title: '2019 ACCA Resume and Cover Letter Writing Guide' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS4.jpg', title: 'Guide to Creating an Online Presence' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS5.jpg', title: 'Application Submit Button on Computer Screen' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS6.jpg', title: 'Follow-up Email Response Illustration' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS7.jpg', title: 'Preparing for Job Interviews: 6 Tips to Get Ready' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS8.jpg', title: 'Flexible Career Advice Illustration' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS9.jpg', title: 'Stay Positive Job Hunting Strategy' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS10.jpg', title: 'Study Last Minute Tips Poster' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS11.jpg', title: 'How to Create a Quick Study Plan for Students' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS12.jpg', title: 'Create Advertisements With Visual Aid Tools' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS13.jpg', title: 'Active Learning Techniques Poster' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS14.jpg', title: 'Use Mnemonics and Acronyms for A-Z' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS15.jpg', title: 'Stay Hydrated and Take Breaks' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS16.jpg', title: 'How to Avoid Distractions During Study' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS17.jpg', title: 'Positive Emoji Reminder' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS18.jpg', title: 'Review Summary and Notes' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS19.jpg', title: 'Online Resource Infographic' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS20.jpg', title: 'Tips for Jadi Productive Poster' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS21.jpg', title: 'Goal Setting Worksheet for Short-term and Long-term Academic Goals' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS22.jpg', title: 'Schedule and Prioritize Tasks' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS23.jpg', title: 'Break Down Study Sessions' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS24.jpg', title: 'Active Learning Methods Infographic' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS25.jpg', title: 'Set Realistic Expectations for Success' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS26.jpg', title: '6 Tips for Organizing Your Study Materials' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS27.jpg', title: '7 Developing Healthy Habits to Improve Wellbeing' },
        { src: 'img/design/socialmedia/INTERNSHIP TIPS28.jpg', title: 'Reflect and Adjust Yourself' },
        { src: 'img/design/socialmedia/ORDER.jpg', title: 'Instructional graphic for online ordering process.' },
        { src: 'img/design/socialmedia/poster cuti.jpg', title: 'Notis Cuti Vertico' },
        { src: 'img/design/socialmedia/POSTER MENJERIT GAMING1.jpg', title: 'Gaming Jersey Designs for Esports Teams' },
        { src: 'img/design/socialmedia/POSTER MENJERIT MERDEKA3.jpg', title: 'Display of Soccer Jerseys and Merchandise' },
        { src: 'img/design/socialmedia/poster pilihanraya1.jpg', title: 'Parliament of Malaysia 2023 Official Portrait' },
        { src: 'img/design/socialmedia/poster pilihanraya2.jpg', title: 'Parliament of Malaysia 2023 Election Promotional Poster' },
        { src: 'img/design/socialmedia/poster pilihanraya3.jpg', title: 'Malaysian Parliament Member 2023 Election' },
        { src: 'img/design/socialmedia/POSTERPROMO.jpg', title: 'Free Design Challenge Poster for Vertika Event' },
        { src: 'img/design/socialmedia/POSTERPROMOKOLARPOST.jpg', title: 'Red Phoenix Promo Jersey Set' },
        { src: 'img/design/socialmedia/POSTERPROMOKOLAR2POST.jpg', title: 'Red Phoenix Soccer Jersey Promotion' },
        { src: 'img/design/socialmedia/POSTERPROMOKOLAR3POST.jpg', title: 'Polo Collar & Long Sleeve Shirt Promotion' },
        { src: 'img/design/socialmedia/POSTERPROMOKOLAR4POST.jpg', title: 'Promotional Advertisement for Sportswear' },
        { src: 'img/design/socialmedia/PRINT FLYERS A5 (6).png', title: 'Creative Design Classes and Services' },
        { src: 'img/design/socialmedia/r1.png', title: 'Racing Logos for Events' },
        { src: 'img/design/socialmedia/r2.png', title: 'Vertico Running Edition' },
        { src: 'img/design/socialmedia/r3.png', title: 'Uniform Samples with Numbered Squares' },
        { src: 'img/design/socialmedia/r4.png', title: 'Minimum Order 5 Helal Sahajan' },
        { src: 'img/design/socialmedia/r5.png', title: 'Colorful Runners Shirts for Vernee Neon Run 2019' },
        { src: 'img/design/socialmedia/r6.png', title: 'Multicolored t-shirts for gaming event' },
        { src: 'img/design/socialmedia/SIZECHART1.jpg', title: 'Vertico Agent Pricelist 2014' },
        { src: 'img/design/socialmedia/SIZECHARTKIDS2.jpg', title: 'Child Size Chart Poster with Body Measurements' },
        { src: 'img/design/socialmedia/SIZECHARTMAN2.jpg', title: 'Size Chart Poster for Verdict Clothing' },
        { src: 'img/design/socialmedia/SIZECHARTMAN3.jpg', title: 'V Vertigo Size Chart Poster' },
        { src: 'img/design/socialmedia/SIZECHARTMUSLIMAH2.jpg', title: 'V Brave Be Bold Size Chart Muslimah' },
        { src: 'img/design/socialmedia/SIZECHARTVARSITY.jpg', title: 'Size Chart for Jacket Variety in Several Asian Languages' },
        { src: 'img/design/socialmedia/SOFT POSTER2.jpg', title: 'Plastic Ban Information Poster' },
        { src: 'img/design/socialmedia/softpoester3.jpg', title: 'Instagram Post with Plastic Bag and Handwritten Text' },
        { src: 'img/design/socialmedia/STUDENT DEALS.jpg', title: 'Student Deals 2021 Poster for Helai Apparel' },
        { src: 'img/design/socialmedia/STUDENT DEALS3.jpg', title: 'Student Deal Flyer for 2024, Roundneck Tees and Shortsleeve Shirts' },
        { src: 'img/design/socialmedia/SUCCESSTORYROZAIRI.jpg', title: 'Successful Online Gaming Tournament Announcement' },
        { src: 'img/design/socialmedia/thumbnail2.jpg', title: 'Tips and Tricks to Overcome Depression' },
        { src: 'img/design/socialmedia/UCAPAN RAYA10.jpg', title: 'Hari Raya Aidilfitri Greeting Card' },
    ],
};